### ISSUE TITLE
[api-extractor] Roll up of default export is not valid TypeScript

### ISSUE THREAD

**Issue by yacinehmito** [Microsoft/web-build-tools#1007]
### Minimal example

Use the following snippet as entry file.

```ts
// index.ts
const example = 'foo'

export default example
```

This outputs:

```ts
// index.d.ts
export declare const default = "foo";
```

There, the TypeScript compiler errors with "Variable declaration expected" because the variable has the name `default`. To solve the issue the file must be manually edited as to match the following:

```ts
declare const example = "foo";

export default example;
```

**Comment by pgonzal** [comment]
Thanks for creating a PR!
