### ISSUE TITLE
[rush] pnpmfile not working for projects in rush.json

### ISSUE THREAD

**Issue by ledniy** [Microsoft/web-build-tools#1009]
Hi, trying to use pnpmfile to fix 'bad packages' in our monorepo and got unexpected behavior that it's not working for project defined in rush.json.
Simple example:
```
git clone https://github.com/ledniy/rush-pnpmfile-project
cd rush-pnpmfile-project
rush update
```

expecting to have `nanoid` in projects/a/node_modules but got only mkdirp

**Comment by iclanton** [comment]
In a rush repo, `pnpmfile.js` can't be used to modify the dependencies of a project inside the repo. The `node_modules` folders of projects inside the repo are actually populated by the `rush link` step (which runs automatically after `rush update`).

In your example, you could add `nanoid` as a dependency of another external package, but if you want to make it a dependency of a project inside the repo, you should just add it to that project's `package.json`.

As an aside - the `@rush-temp/*` packages are an implementation detail of rush and aren't intended to be used by anything except for the rush API. You're likely to run into unexpected behavior if you use them for anything.

**Comment by ledniy** [comment]
@iclanton ok, make sense
