### ISSUE TITLE
[api-extractor] Error: Program Bug: The symbol ReactNode is being imported after it was already registered as non-imported

### ISSUE THREAD

**Issue by CarstenLeue** [Microsoft/web-build-tools#1047]
I am facing an issue that seems to be related to #847 . When running `api-extractor` on a project with just this export:

```typescript
import { createElement, ReactNode } from 'react';

export function createLibElement(): ReactNode {
  return createElement('div');
}
```

It get the error
```
Error: Program Bug: The symbol ReactNode is being imported after it was already registered as non-imported
```

I have created a minimal repo to reproduce: https://github.com/CarstenLeue/api-extractor-react

**Comment by pgonzal** [comment]
Thanks for providing a repro branch!

**Comment by CarstenLeue** [comment]
Awesome, thanks so much. I am now installing as `@microsoft/api-extractor@^7` and that works like a charm.
