### ISSUE TITLE
[api-extractor] No way to disable tsdoc metadata

### ISSUE THREAD

**Issue by alan-agius4** [Microsoft/web-build-tools#1051]
It would be useful to provide an options to disable the generation of tsdoc metadata file.

**Comment by pgonzal** [comment]
Looks like this is fixed in PR https://github.com/Microsoft/web-build-tools/pull/1011

**Comment by octogonz** [comment]
That PR was merged and published, so I assume this issue is now resolved.  If not, please reopen and give more details.  Thanks!
