### ISSUE TITLE
[api-documenter] Parameters of top level functions and parameter names using Finnish notation are not documented

### ISSUE THREAD

**Issue by CarstenLeue** [Microsoft/web-build-tools#1055]
I have a top level function like this
```typescript
/**
 * Doc of my exported function
 *
 * @param aParam - first parameter
 * @param aObs$ - second parameter
 * @returns the return value
 */
export function myFunction(aParam: string, aObs$: Observable<string>): string {
  return '';
}
```

and a member function like this:
```typescript
export class MyClass {
  /**
   * Doc of my exported function
   *
   * @param aParam - first parameter
   * @param aObs$ - second parameter
   * @returns the return value
   */
  myFunction(aParam: string, aObs$: Observable<string>): string {
    return '';
  }
}
```

I find that none of the parameters or the return value of the top level function get documented. For the member function the second parameter using Finnish notation is not being documented.

Versions:

`api-extractor 7.0.13`
`api-documenter 7.0.19`

This seems to be related to #970 .

Repository to reproduce:
https://github.com/CarstenLeue/api-extractor-doc

**Comment by CarstenLeue** [comment]
@pgonzal thanks for the quick turnaround. I removed the trailing '$' character from the sample repo (https://github.com/CarstenLeue/api-extractor-doc). 

Result: 
- the class method is documented as expected. I'll open a defect for https://microsoft.github.io/tsdoc/
- the top level function is still not documented at all

**Comment by CarstenLeue** [comment]
@pgonzal any updates on the problem that top level functions are not being documented?

**Comment by octogonz** [comment]
Fixed by PR https://github.com/Microsoft/web-build-tools/pull/1057

**Comment by CarstenLeue** [comment]
I confirm that this is fixed, thanks!
