### ISSUE TITLE
[api-extractor] Unsupported export error after updating

### ISSUE THREAD

**Issue by haroldma** [Microsoft/web-build-tools#1068]
Using version 7 and getting this:
```
Error - 'api-extractor' sub task errored after 6.68 s
 Unsupported export "BabylonFileParser" in [C:/Users/haroldma/Documents/repos/sp-client - Copy/common/temp/node_modules/.onedrive.pkgs.visualstudio.com/babylonjs/4.0.0-alpha.22/node_modules/babylonjs/babylon.module.d.ts#33477]
```

The typings file for babylon.js is [here](https://raw.githubusercontent.com/BabylonJS/Babylon.js/e54ff6e4e2c9abce8e37f47efd9c0e2d4713dbf6/dist/preview%20release/babylon.module.d.ts)

----

This was working fine before the update.

**Comment by octogonz** [comment]
We should use this as a test case for PR https://github.com/Microsoft/web-build-tools/pull/1077

**Comment by haroldma** [comment]
Sweet, I'll keep an eye on it.

**Comment by octogonz** [comment]
@haroldma Could you retest this with 7.0.19 and let us know if it's still broken?  If so, please provide an easy repro.

**Comment by haroldma** [comment]
Oh yeah, this works fine on our end. Forgot to close this. Thanks!
