### ISSUE TITLE
[api-extractor] links are broken on "Enabling for your project" documentation

### ISSUE THREAD

**Issue by craigkovatch** [Microsoft/web-build-tools#1074]
At https://github.com/Microsoft/web-build-tools/wiki/API-Extractor-~-Enabling-for-your-project, the three files linked in this text are 404s:

```
More information about this file format:

api-extractor.schema.json - the JSON schema

IExtractorConfig.ts - TypeScript interfaces for the JSON schema

api-extractor-defaults.json - the default values

Finally, compile your project and then invoke the api-extractor tool in your project folder, like this:```

**Comment by octogonz** [comment]
That content was moved here:  https://api-extractor.com/pages/setup/get_started/

Hmmm I thought we deleted those wiki pages.  I'll go delete them now.

**Comment by octogonz** [comment]
Fixed.
