### ISSUE TITLE
[api-documenter] references to external documentation lead to missing statements in the doc

### ISSUE THREAD

**Issue by CarstenLeue** [Microsoft/web-build-tools#1082]
I have my interface documented like this:

```typescript
/**
 * State that covers the {@link @ibm-wch-sdk/api:UrlConfig | configuration} of the URLs to be used
 * when working with {@link https://developer.ibm.com/api/view/dx-prod:ibm-watson-content-hub:title-IBM_Watson_Content_Hub | WCH REST} services.
 *
 * @remarks
 * Note that all URLs in this object are guaranteed to be absolute URLs and to end with a trailing slash.
 */
export type UrlConfigState = UrlConfig;
```

This results in the following markdown for the doc:
```markdown
## UrlConfigState type

State that covers the  of the URLs to be used when working with [WCH REST](https://developer.ibm.com/api/view/dx-prod:ibm-watson-content-hub:title-IBM_Watson_Content_Hub) services.

<b>Signature:</b>

export declare type UrlConfigState = UrlConfig;

## Remarks

Note that all URLs in this object are guaranteed to be absolute URLs and to end with a trailing slash.
```

Note that the word `configuration` is missing from the documentation. 

The cross referenced package `@ibm-wch-sdk/api` does contain a `api.json` as part of its distribution. But even if it would not I would expect the documented word to show up, but just not have a link to the documentation. This way it breaks the readability of the comment.

Referring to [external references](https://api-extractor.com/pages/tsdoc/syntax/#api-item-references)

**Comment by octogonz** [comment]
I think the underlying issue is that `{@link @ibm-wch-sdk/api:UrlConfig | configuration}` needs a `#` delimiter to be `{@link @ibm-wch-sdk/api#UrlConfig | configuration}`. In older versions we did use `:` but we needed the colon for the new TSDoc selector notation that enables references to function overloads and such.

Obviously API Extractor's handling of this should be more intuitive.

**Comment by octogonz** [comment]
FYI you can paste code comments into https://microsoft.github.io/tsdoc/ to get a better idea how they are parsed.

**Comment by CarstenLeue** [comment]
@octogonz thanks. In that case I suggest to fix the documentation: https://api-extractor.com/pages/tsdoc/syntax/#api-item-references

After upating to `{@link @ibm-wch-sdk/api#UrlConfig | configuration}` I get the error message:

`WARNING: Unable to resolve reference: The package "@ibm-wch-sdk/api" could not be located`

It looks like `tryGetPackageByName` in `ApiModel` does not contain that package. But how is it supposed to become available? Do I need to register the dependency in any way?

My source file contains the package as an import statement:
```typescript
import { UrlConfig } from '@ibm-wch-sdk/api';

/**
 * State that covers the {@link @ibm-wch-sdk/api#UrlConfig | configuration} of the URLs to be used
 * when working with {@link https://developer.ibm.com/api/view/dx-prod:ibm-watson-content-hub:title-IBM_Watson_Content_Hub | WCH REST} services.
 *
 * @remarks
 * Note that all URLs in this object are guaranteed to be absolute URLs and to end with a trailing slash.
 */
export type UrlConfigState = UrlConfig;

```

**Comment by octogonz** [comment]
This warning is coming from **api-documenter** not **api-extractor**, right?

When you invoke **api-documenter**, the `--input-folder` needs to contain the full set of .api.json files that you want to appear on your web site. Typically your build definition will build/install packages and then copy these files into a central folder. Links will only be matched if they can be found in this data set. The `ApiPackage` object represents one of these .api.json files, and `ApiModel` is the collection of all of them.

**Comment by octogonz** [comment]
Btw the docs have a button "Improve this page" if you'd like to fix the colon in the example.  :smile:

We were waiting for API Extractor 7 do be released before documenting the new TSDoc tags in depth.

**Comment by CarstenLeue** [comment]
@octogonz I'll make a pull request for the doc.

I am confuses however about "... needs to contain the full set ...". If I do that, then the documentation of my project contains a full copy of the documentation of the referenced projects. This can be huge.

My intent was to link to the other projects' documentation.
The `api-documenter` doc says:
> The external package must be installed in your node_modules folder, and must include an *.api.json file generated by API Extractor.

According to that doc, it would not be required to copy external api descriptions into the input folder. Reading that doc my expectation would have been that `api-documenter` generates a link to the repo of the referenced doc.

Is this a flaw in the documentation? What's the expected behaviour for external referenced, will I really have to include a full copy?

**Comment by CarstenLeue** [comment]
https://github.com/Microsoft/api-extractor.com-website/pull/4

**Comment by octogonz** [comment]
> I am confused however about "... needs to contain the full set ...". If I do that, then the documentation of my project contains a full copy of the documentation of the referenced projects. This can be huge.

The **api-documenter** tool is designed to generate a centralized API web site for packages that may come from different teams, possibly working in different repos, maybe with different ways of publishing their APIs.  Thus, the intended workflow is like this:

1. Create some folder `C:\docs` (that is not itself a TypeScript folder or NPM package)
2. Collect the `*.api.json` files from all the various packages that you want to document, and dump them in `C:\docs\input`
3. Run the **api-documenter** tool once, which produces a bunch of files in `C:\docs\markdown` and/or `C:\docs\yaml`
4. Deploy these files to the web site

Typically this process would be part of an automated workflow.  At Microsoft, people usually track `C:\docs\input` using Git so it's easily to see the history of changes to the web site content.  The web site may be an important deliverable to a commercial audience, so the editorial process may be different from the code review that is performed for a regular PR.  It may involve technical writer people or program managers.  The copying of the **.api.json** files may be timed to coordinate with a release announcement.  If you decide that you don't want to document a particular package (e.g. the docs for a new package don't meet the quality bar), you can simply delete that *.api.json file from the `C:\docs\input` folder, and **api-documenter** will still produce a valid output, and omitting any hyperlinks to those APIs.

Let me know if you think we should document this better, and if so which aspects of the process are unclear.

**Comment by CarstenLeue** [comment]
@octogonz thanks for the explanation. I intend to use the documentation somewhat differently, since the generated documentation will be part of the documented npm module itself, not hosted on an external website. So I was hoping to have a way to link to the documentation of a different project, without having to copy that documentation. 
But it's also ok the way it is, I get the rationale.

You might want to clarify on this point on the website: https://api-extractor.com/pages/tsdoc/syntax/#api-item-references

So far it reads `For external references...` . To me this sounded as if a documentation can contain references to external documentation.

**Comment by octogonz** [comment]
> You might want to clarify on this point on the website

Thanks for this suggestion - will do.

**Comment by octogonz** [comment]
I updated the website to clarify this point.
