### ISSUE TITLE
[api-extractor] transitively-included types aren't emitted in api.ts

### ISSUE THREAD

**Issue by craigkovatch** [microsoft/web-build-tools#1097]
I feel nervous writing this one because it seems more likely that *I'm* doing something wrong than the api-extractor. Please educate me if so. Using beta version 7.0.17.

I have a file `DateInputField.tsx` shaped like this:

```
import { DateTerminus } from '../utils/Date';

/** @public */
export enum DateFormat {
  ShortDateTime,
  MediumDateTime,
  ...
}

/** @public */
export enum DateInputFieldType {
  Line,
  Outline,
}


/** @public */
export interface DateInputFieldProps extends Pick<OverlayProps, 'stackingRootId' | 'zIndex'> {
  dateInputFieldType?: DateInputFieldType;
  disabled?: boolean;
  displayFormat?: DateFormat;
  terminus?: DateTerminus;
}

export interface DateInputFieldState {
  inputText: string;
  isDatePickerOpen?: boolean;
}

/** @public */
export class DateInputField extends React.Component<DateInputFieldProps, DateInputFieldState> { }
```

In the top-level "entry point" file I have:
```
export { DateInputFieldType, DateInputFieldProps, DateInputField } from './widgets/DateInputField';
```

In the output of `project.api.ts`, the `DateInputFieldType` enum is output, but the `DateTerminus` and `DateFormat` enums are not.

Is this expected? Since I am explicitly exporting `DateInputFieldProps` which references all three of these enums, I would expect all three to be transitively included in the API output.

**Comment by octogonz** [comment]
Right, in AE6 you would see a warning telling you that you forgot to export `DateTerminus` from your entry point.  We need to reintroduce this warning in AE7.  It's not much code -- seems like I should get that done asap since it seems to be causing a lot of confusion.

The forgotten types _should_ appear in the .d.ts rollup, however.

**Comment by craigkovatch** [comment]
The paradigm here is a little confusing for me. Currently we have certain internal interfaces which are *not* top-level exports on purpose. For example, `ButtonBaseProps` that other prop interfaces extend, or `*State` which we don't expose because React State should not be accessible from outside the relevant component. We intentionally don't export these types from the top-level entry point because we don't want someone to e.g. `const props: ButtonBaseProps`. What's the right way to address this in an `api-extractor` world?

**Comment by octogonz** [comment]
Could you provide a minimal repro that captures the API design idea you're describing here? (i.e. with some realistic names that imply expectations about what should/shouldn't be reachable.) Maybe there's a gap in our design. I can consider this case when I reintroduce the warning.

**Comment by octogonz** [comment]
(Btw sorry about this laziness regarding the investigation; I've got a lot going on right now.)

**Comment by craigkovatch** [comment]
@octogonz what branch should I fork to give you a repro branch?

**Comment by octogonz** [comment]
If you want to use **web-build-tools**, the master branch is fine. All the important recent PRs have been merged and published as of yesterday.

But for your repro, most people just create a blank repo using their personal GitHub, and install **api-extractor** via NPM.  Really I just need something that I can build using `tsc`, and which has an **api-extractor.json** set up for it.

**Comment by octogonz** [comment]
> in AE6 you would see a warning telling you that you forgot to export `DateTerminus` from your entry point. We need to reintroduce this warning in AE7. It's not much code -- seems like I should get that done asap since it seems to be causing a lot of confusion.

BTW the forgotten export warning is reintroduced in [PR 1126](https://github.com/Microsoft/web-build-tools/pull/1126).

**Comment by octogonz** [comment]
@craigkovatch were you able to isolate a repro?  Currently there isn't any straightforward action we can take for this issue.

**Comment by halfnibble** [comment]
Closing this due to related PR being merged and no additional input received. If there is still a question about this, please reopen.
