### ISSUE TITLE
[rush] On errors, could `rush build` print underlying tool's stdout when stderr is empty?

### ISSUE THREAD

**Issue by hogmoru** [Microsoft/web-build-tools#1101]
In my project that uses Webpack, in case of build errors, `rush build` does not show Webpack's error messages:

- [Webpack does not use stderr](https://github.com/webpack/webpack/issues/1278) (which is a pity), errors are printed to stdout
- `rush build`, when the build tool fails (exits with non-zero status), will print tool's stderr
- So, `rush build` does not show Webpack errors, you have to use rush `build -v`.

**In case of build failure, if stderr is empty, could Rush print stdout instead?**

One could argue that Webpack needs fixing, and I would agree, but I bet that Webpack is not the only one to behave that way, so IMHO it would make sense to do something in Rush.

(Please educate me if I'm doing something wrong, with Rush or GitHub or anything)

I published a [quick repro here](https://github.com/hogmoru/rush-webpack-repro/) if needed.

Also have a PR that will follow (good thing that `TaskRunner.ts` has unit tests now :wink: ).

**Comment by octogonz** [comment]
I like this idea.
