### ISSUE TITLE
[rush] Let rush manage the node version in the runtime

### ISSUE THREAD

**Issue by lijunle** [Microsoft/web-build-tools#1109]
Currently, rush has [the limitation](https://github.com/Microsoft/web-build-tools/blob/master/apps/rush/src/start.ts#L13-L36) to run on a couple of node versions. It can use the `npx -p node@10 -p @microsoft/rush -- rush install` to make `rush` run on a specific node version. However, why rush not makes a further step to manage the node version with [node](https://www.npmjs.com/package/node) package. So the host's node can always install the latest version.

**Comment by octogonz** [comment]
I'm not sure if this would work.  The **node_modules** folder is NOT portable between NodeJS runtimes.  For example, if you install binary packages such as sass using Node6 and then try to execute them using Node8, it will fail, saying that the runtime bindings did not match correctly. (I forget the exact error message.)

So if Rush swaps out the Node engine with a specific version while running `rush install`, the shell's Node engine may be a different version that causes compatibility problems when people run commands such as `gulp`.

**Comment by lijunle** [comment]
I suppose the node_modules folder is managed by rush too. So theoretically, they can be downloaded/installed after rush prepared the specific node version. No?

**Comment by octogonz** [comment]
Yes, but that's the problem: Rush can control the NodeJS version for `rush install` and `npm install`, but not for commands like `gulp` or `jest`. In order to do that it would need to control your command shell somehow.

**Comment by octogonz** [comment]
Also, there are many ways to install NodeJS (nvm, nodist, dpkg, etc). It might be presumptive to assume that `npx`'s feature will be appropriate for all users.

**Comment by lijunle** [comment]
Good concerns! It makes sense to leave node version out of rush's scope.
