### ISSUE TITLE
[api-extractor] tsconfig.json "extends" field has to be a relative path

### ISSUE THREAD

**Issue by jakob101** [Microsoft/web-build-tools#1121]
Hi, I have a tsconfig.json file that extends a package:

```
{
  "extends": "@mypackage/tsconfig.default.json",
  "compilerOptions": {
    ...
},
```

However, api-extractor fails with:
```
@microsoft\api-extractor\lib\api\Extractor.js:62
                    throw new Error(`Error parsing tsconfig.json content: ${errorText}`);
                    ^

Error: Error parsing tsconfig.json content: A path in an 'extends' option must be relative or rooted, but '@mypackage/tsconfig.default.json' is not.
```

**Comment by asmundg** [comment]
Extends supports node module resolution as of TypeScript 3.2: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#tsconfigjson-inheritance-via-nodejs-packages, so it seems reasonable that api-extractor should have the same behavior.

**Comment by octogonz** [comment]
Related to issue https://github.com/Microsoft/web-build-tools/issues/1017

**Comment by octogonz** [comment]
@jakob101 actually there is a mistake in your file: `@mypackage` is not a valid NPM package name. It looks like an NPM scope.  For example, a valid name might be `mypackage` or `@myscope/mypackage`.

If you fix that, then the `extends` resolution works as you expected.

Please feel free to reopen this issue if I missed something.  Thanks!

**Comment by tylerbutler** [comment]
I am still hitting this error in some of my projects with v7.0.40. This is the error:

```
Error: Error parsing tsconfig.json content: A path in an 'extends' option must be relative or rooted, but '@myscope/build-common/ts-common-config.json' is not.
```

I can workaround this by updating my package.json to be:

```json
{    
    "extends": "./node_modules/@myscope/build-common/ts-common-config.json",
    "exclude": [
        "dist",
        "node_modules"
    ],
    "compilerOptions": {
        "strict": false,
        "rootDir": "./src",
        "outDir": "./dist",
        "types": [ "mocha" ]
    },
    "include": [
        "src/**/*"
    ]
}
```

**Comment by Delagen** [comment]
@tylerbutler I prepare tsconfig via typescript and pass it to extractor api, so it works. You can use it if suitable.

**Comment by octogonz** [comment]
> I prepare tsconfig via typescript and pass it to extractor api, so it works. You can use it if suitable.

@Delagen this will work, but it has the downside that you can't run the `api-extractor` command-line tool in your project folder.  The command-line can sometimes very useful for diagnosing problems, or e.g. if you wanted to debug API Extractor itself.  In the future we're planning to add a command like `api-extractor dump-config` that will help people understand how their `<projectFolder>` tokens and `extends` fields were processed.  Just something to think about...

**Comment by octogonz** [comment]
> I am still hitting this error in some of my projects with v7.0.40. This is the error:
> 
> ```
> Error: Error parsing tsconfig.json content: A path in an 'extends' option must be relative or rooted, but '@myscope/build-common/ts-common-config.json' is not.
> ```

@tylerbutler The projects in this repo rely heavily on tsconfig.json `extends` fields.  (For example [node-core-library/tsconfig.json](https://github.com/Microsoft/web-build-tools/blob/83917c9de78a0298164c8dd86a40739f0e30da33/libraries/node-core-library/tsconfig.json#L2).)  So it definitely seems to be working correctly.

If you're still having trouble, could you reopen this issue and provide a complete repro (e.g. a GitHub branch with build instructions)?  That would help us to investigate.

**Comment by tylerbutler** [comment]
@octogonz I just looked at the example you linked:

```
"extends": "./node_modules/@microsoft/rush-stack-compiler-3.2/includes/tsconfig-node.json",
```

If I prefix the string with `./node_modules/`, it works (which is what I am doing as a workaround), but that shouldn't be required, right?

**Comment by octogonz** [comment]
@tylerbutler Oh right - I overlooked that detail.

I do recall that only certain newer versions of the compiler have this feature. API Extractor uses the compiler itself to parse tsconfig.json, so it should work.

Can you try AE 7.0.41? That release upgrades the internal engine to TypeScript 3.4 which might help.

**Comment by octogonz** [comment]
You said the feature was introduced in 3.2. 7.9.40 was using TypeScript 3.1.  So that probably explains it. (It's important to understand that AE comes with its own compiler installation that is separate from whatever version your project is using to build.)

**Comment by tylerbutler** [comment]
@octogonz I can no longer repro with 7.0.41. :) The TS 3.4 update resolved a number of issues for me. Thanks!
