### ISSUE TITLE
[rush] Add support for PNPM Version 3

### ISSUE THREAD

**Issue by wbern** [microsoft/web-build-tools#1145]
As title says, there are a few breaking changes for this release.

https://github.com/pnpm/pnpm/releases

**Comment by octogonz** [comment]
Damn... the config file names have changed:

> shrinkwrap.yaml -> lockfile.yaml

Rush uses the term "shrinkwrap" generically for all package managers.  I guess we'll need to update that, too.

**Comment by octogonz** [comment]
The PNPM filename is in [RushConstants.ts](https://github.com/Microsoft/web-build-tools/blob/904e6980a6ec79de535965a926269bc7a4ae4876/apps/rush-lib/src/logic/RushConstants.ts#L75).

Rush has been using the term "shrinkwrap file" to refer generically to this file across NPM/Yarn/PNPM.  This was the name originally used by NPM, but if all the package managers are now calling it a "lock file", we should update our terminology.  (This term "lock file" has a different, widely established meaning in the software industry that predates Ruby GEM and even the JavaScript language.  Maybe Rush should call it something like "version lock file" or "package lock file" to avoid ambiguity.)

This fix should not break support for PNPM 2.x, so it seems like we need to select the filename based on [pnpmVersion](https://github.com/Microsoft/web-build-tools/blob/2e612a6c07494ef7d4d26c3f0bdeacd5c1208e9a/apps/rush-lib/src/api/RushConfiguration.ts#L108).

**Comment by tnc1997** [comment]
I managed to make a start adjusting the `rush-lib` app in order to support both `shrinkwrap.yaml` (v2) and `pnpm-lock.yaml` (v3) files as per the differing versions of pnpm. Feel free to take a look at the changes, which continue on from those mentioned in #1180, in my [fork](https://github.com/tnc1997/web-build-tools/tree/tnc1997/pnpm-version-3).

**Comment by octogonz** [comment]
In [a gitter thread](https://gitter.im/web-build-tools/web-build-tools?at=5ca72278b34ccd69e76a0f4a) @poelstra suggested that Rush should print an error if the package manager didn't create the filename that it was expected to create.  Without that, he had a really confusing experience where he tried the "latest" version of PNPM and it mysteriously succeeded but there wasn't any shrinkwrap file.

**Comment by Toxaris** [comment]
I just had a similar "really confusing experience" where `rush install` was failing in the CI so I locally run `rush update && rush install` and the latter complained that I need to run `rush update` again.

We're considering to switch from lerna+yarn to rush+pnpm in our monorepo and I'm following https://rushjs.io/pages/maintainer/setup_new_repo/ which tells me to "check that you’re using recent stable releases for any other applicable fields such as `pnpmVersion`".

A pointer from the documentation to this issue would have been appreciated. Or maybe https://rushjs.io/pages/maintainer/package_managers/ could mention the most recent pnpm version that is "known to work".

**Comment by bsiegel** [comment]
Is this completed by #1210?

**Comment by octogonz** [comment]
Yup
