### ISSUE TITLE
[rush] "rush change" fails to fetch origin/master in certain situations

### ISSUE THREAD

**Issue by octogonz** [microsoft/web-build-tools#1177]
Repro steps:

1. Clone **web-build-tools**, then rollback your `origin/master` to commit hash e444346f4e922a374cfc95a381d6b962e9b873e0.
2. Now add a remote for `raygesualdo:partial-prereleases` from PR https://github.com/Microsoft/web-build-tools/pull/1175.
3. Rewind the `partial-prereleases` branch to commit hash 8cee308b7948cac641a9c3de62783c861d37f601
4. Run `rush change`

**Expected:** It should prompt for changes for the **@microsoft/rush** project only.
**Actual:** `rush change` wants change longs for ALL projects in the repo.

**What's going on:**  The `rush change` command invokes [VersionControl.getChangedFolders()](https://github.com/Microsoft/web-build-tools/blob/d21ed494711a891eb8631999d66bb423e397ff3c/apps/rush-lib/src/utilities/VersionControl.ts#L13) which executes this command:

```sh
git diff origin/master... --dirstat=files,0
```

But it finds a huge diff because **origin/master** is not up to date.  Before running this command, `rush change` was supposed to fetch changes using [VersionControl._fetchNonDefaultBranch()]():

```ts
  private static _fetchNonDefaultBranch(remoteBranchName: string): void {
    // NOTE: DEFAULT_FULLY_QUALIFIED_BRANCH is "origin/master"
    if (remoteBranchName !== DEFAULT_FULLY_QUALIFIED_BRANCH) {
      console.log(`Checking for updates to ${remoteBranchName}...`);
      const fetchResult: boolean = VersionControl._tryFetchRemoteBranch(remoteBranchName);
      if (!fetchResult) {
        console.log(colors.yellow(
          `Error fetching git remote branch ${remoteBranchName}. Detected changed files may be incorrect.`
        ));
      }
    }
  }
```

However, the fetching is skipped because `remoteBranchName === "origin/master"`.  If I delete the if-statement, then the changes are fetched, the diff is correct, and `rush change` prompts for changes ONLY for the **@microsoft/rush** project.

(Thanks https://github.com/Microsoft/web-build-tools/pull/1175#issuecomment-475775279 for reporting this!)

**Comment by octogonz** [comment]
@iclanton FYI since you worked on `rush change` recently.

**Comment by iclanton** [comment]
This has been fixed. I'll close this issue when it's released.
