### ISSUE TITLE
[rush] update rush.json schema and documentation

### ISSUE THREAD

**Issue by raygesualdo** [Microsoft/web-build-tools#1182]
The `rush.json` documentation at `https://rushjs.io/pages/configs/rush_json/` and schema at `https://developer.microsoft.com/json-schemas/rush/v5/rush.schema.json` are both out of date. I was specifically looking for `gitPolicy.versionBumpCommitMessage` but there may be other aspects of the documentation that are missing as well.

**Comment by octogonz** [comment]
The web site is fixed in https://github.com/Microsoft/rushjs.io-website/commit/7fac3ee5474fa5a79eb57a13dd5738c4616d1f02

**Comment by octogonz** [comment]
The JSON schema will be fixed by https://github.com/Microsoft/json-schemas/pull/19

**Comment by raygesualdo** [comment]
Y'all are on it! Thanks!
