### ISSUE TITLE
[rush] Suggestion: Erroring build summary should include error output

### ISSUE THREAD

**Issue by nfour** [microsoft/web-build-tools#1191]
When running `rush build -v` on a large repo, I've found it's often difficult to locate the error output based on the summary.

The build script for a project may resemble:

```json
"build": "yarn tslint && yarn tsc && yarn jest",
```

If `tsc` were to fail, I currently see this (with or without --verbose):

```
FAILURE (1)
================================
my-service (19.95 seconds)
strict-type-predicates does not work without --strictNullChecks
error Command failed with exit code 2.
error Command failed with exit code 2.
================================
```

and would like to see this:

```
FAILURE (1)
================================
my-service (19.95 seconds)
strict-type-predicates does not work without --strictNullChecks
Starting type checking service...
Using 1 worker with 2048MB memory limit
webpackbar 11:13:16 ℹ Compiling Webpack
webpackbar 11:13:26 ✔ Webpack: Compiled with some errors in 9.29s
Child
    ERROR in .../middlewares.ts(22,5):
    TS2304: Cannot find name 'ISearchFilter'.
error Command failed with exit code 2.
error Command failed with exit code 2.
================================
```

We currently are using:
- `rush@5.6`
- `pnpm@2.25`

**Comment by octogonz** [comment]
Is the problem that the details you want to see are being written to stdout instead of stderr? Rush's error summary only prints stderr, because stdout can often have a large volume of console output that would be inappropriate in an error summary.

**Comment by nfour** [comment]
@octogonz Okay so rush actually outputs stderr, but perhaps `tsc` etc. is not outputting to stderr and thus it's not coming through.

Will have to check this.

**Comment by nfour** [comment]
Sorry about this - seems like it's an issue with Jest, not rush. Jest by default outputs to stderr, and requires the use of a different reporter to fix this oversight.
