### ISSUE TITLE
Fails when running if a package.json is missing "name" (Discord.JS)

### ISSUE THREAD

**Issue by lakeshadow0** [Microsoft/web-build-tools#1200]
When running ``api-extractor`` with the following configuration

```json
{
    "$schema": "https://developer.microsoft.com/json-schemas/api-extractor/api-extractor.schema.json",
    "compiler": {
        "configType": "tsconfig",
        "rootFolder": "."
    },
    "project": {
        "entryPointSourceFile": "build/src/index.d.ts"
    }
}
```
where a package.json exists without a name, the extractor fails. This happens specifically with the Discord.JS package. 

```
$api-extractor run

api-extractor 6.3.0  - http://aka.ms/extractor

Using configuration from *...\api-extractor.json


Error: Error reading "...\node_modules\discord.js\typings\package.json":
  The required field "name" was not found
```

where the package.json's contents are

```json
{
  "devDependencies": {
    "tslint": "^3.15.1",
    "tslint-config-typings": "^0.2.4",
    "typescript": "^2.2.1"
  },
  "scripts": {
    "lint": "tslint index.d.ts discord.js-test.ts"
  },
  "dependencies": {
    "@types/node": "^7.0.0"
  }
}
```

To get around this temporarily, I simply added a name. This then caused an error to be thrown for missing ``version`` as well.

**Comment by octogonz** [comment]
The `version` field is now optional in API Extractor 7, because even though this violates the NPM spec, it is apparently technically permitted by NodeJS. The `name` field is absolutely required as far as I know, so if Discord is omitting it, then Discord has a bug.

**Comment by octogonz** [comment]
I'm closing this because (1) the missing `version` field is fixed in AE7 and (2) the missing `name` field seems like an external issue with Discord.JS.

Please feel free to reopen the issue if you have further comments/concerns.  Thanks!

**Comment by umidbekkarimov** [comment]
@octogonz Some modules use intermediate `package.json` files that used by bundlers to enhance tree shaking https://unpkg.com/browse/@material-ui/core@4.3.1/AppBar/package.json.

In that case, there will be no `version` or `name` property.

I dived into the code and found that parsing of `package.json` required only to parse `tsdocMetadata`, and only a few fields needed for it (`tsdocMetadata`, `typings`, `types` and `main`) https://github.com/microsoft/web-build-tools/blob/master/apps/api-extractor/src/analyzer/PackageMetadataManager.ts#L74-L104.

Maybe it's worth to update `package.json` identification policy?

**Comment by Pymossy** [comment]
Hi,
Does anybody suggest a workaround?
Thank you

**Comment by octogonz** [comment]
Make a valid package.json?

**Comment by Pymossy** [comment]
I think it is better to ignore invalid package.json in subfolders

**Comment by octogonz** [comment]
Are you able to share a repro of your problem? If so, please open a new GitHub issue and I can investigate it.

**Comment by gregjoeval** [comment]
Was there a solution or separate issue opened to handle the invalid package.json files? (specifically for material-ui)

**Comment by octogonz** [comment]
@gregjoeval  My opinion is:

> Make a valid package.json

If that isn't possible for some reason, then:

> Are you able to share a repro of your problem? If so, please open a new GitHub issue and I can investigate it.

**Comment by gregjoeval** [comment]
Here is the new issue: #2070
