### ISSUE TITLE
[rush] Using pnpm & webpack, some modules are unexpectedly included multiple times

### ISSUE THREAD

**Issue by elliottsj** [microsoft/web-build-tools#1219]
Full description in https://github.com/elliottsj/rush-pnpm-webpack-duplicate-module-issue

Like #1142, this seems to happen when using Rush + pnpm, but does not occur when using just pnpm.

I'm hoping this will be resolved by #1180

**Comment by octogonz** [comment]
@iclanton do you have time to review https://github.com/Microsoft/web-build-tools/pull/1210?

**Comment by octogonz** [comment]
Closing this because it should be solved by the new `resolutionStrategy=fewer-dependencies` setting in **rush.json**. That feature was introduced by Rush 5.7.x and is enabled by default.

Please reopen this issue if it did not solve your problem.  Thanks!
