### ISSUE TITLE
[api-extractor] Add support for TypeScript 3.4

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/web-build-tools#1221]
TypeScript 3.4 was released a couple of weeks ago, and it brings with it [incremental build support](https://devblogs.microsoft.com/typescript/announcing-typescript-3-4/#faster-subsequent-builds-with-the---incremental-flag).

My project is already taking advantage of the build time improvements, and I imagine other TypeScript projects will follow quickly given the benefits.

**Comment by octogonz** [comment]
We can reuse this PR that was opened for 3.3.3333: https://github.com/Microsoft/web-build-tools/pull/1124

The RSC issue is not difficult to fix, but @iclanton and I have been super busy the past couple weeks.  I'll try to get to it ASAP.

**Comment by octogonz** [comment]
@tylerbutler I have merged PR #1124, so this is now fixed.
