### ISSUE TITLE
[api-extractor] Add option to specify path to tsconfig.json

### ISSUE THREAD

**Issue by tylerbutler** [Microsoft/web-build-tools#1222]
As a possible workaround to #1221, I tried creating a new tsconfig-api-extractor.json file which omitted the `incremental` flag. But it seems that there's no way to tell api-extractor to use a particular tsconfig file.

**Comment by octogonz** [comment]
This is a good suggestion.  As a workaround you could add the entire contents of your tsconfig.json to the `overrideTsconfig` field.

**Comment by octogonz** [comment]
@tylerbutler FYI PR #1225 adds this feature.

**Comment by octogonz** [comment]
This feature was published with the API Extractor beta release 7.0.41
