### ISSUE TITLE
[rush] Cli action to list projects

### ISSUE THREAD

**Issue by Shubham-2k17** [microsoft/web-build-tools#1242]
cli action like `rush projects` which can list package names from configuration will be really helpful. Right now we have to look through `rush.json` to see list of projects.

Good starting point will be to have **ProjectsAction** in `web-build-tools/apps/rush-lib/src/cli/actions/`

**Comment by octogonz** [comment]
```ts
      const projects: string[] = this.rushConfiguration.projects.map(
        project => project.packageName
      );
```
@Shubham-2k17 this command seems useful, but I'm wondering if we should provide a way to configure the property that is printed.  For example, if there was a CLI enum like `rush projects --field FIELD`, then you could imagine some different useful possibilities:

- `--field name`  - package name (`project.packageName`)
- `--field name-and-version` - package name followed by tab followed by current version (`"version"` field from package.json)
- `--field folder` - absolute path to the package folder (`project.packageFolder`)
- `--field relative-folder` - relative path to the package folder (`project.projectRelativeFolder`)

We don't necessarily need to implement all of these today.  But for the CLI design, if we had this `--field` option, I'm wondering whether `name` is the best thing to show by *default* when `--field` is omitted.

@iclanton

**Comment by octogonz** [comment]
The `--field name-and-version` idea could also be represented as a ts-command-line array (`rush projects --field name --field version`), i.e. allowing multiple field names to be chosen, and the output is delimited by TAB characters or somesuch that can easily be parsed by another tool.

**Comment by Shubham-2k17** [comment]
Nice idea, will look into it.
