### ISSUE TITLE
[rush] Does Rush only work with Git?

### ISSUE THREAD

**Issue by vman** [Microsoft/web-build-tools#1250]
Does Rush only work with Git change tracking? I see the getting started tutorial does a `git add .` on any projects being added to the monorepo and #271 also confirms this.

But on this page https://rushjs.io/pages/maintainer/setup_new_repo/ the descriptions for the `.gitattributes` and `.gitignore` files contains the text: _Delete this file if you’re not using Git._

So is this a documentation bug?

**Comment by octogonz** [comment]
Practically speaking, the entire web community seems to be a Git monoculture. Early on we talked about supporting Mercurial or SVN, but not one person has ever asked for that (so far). No effort has been invested to support it.

However, it should be possible to use Rush in a folder that is not tracked by Git. For example, if I send you a zip archive containing a folder, you should be able to run "rush install" or "rush build" without having to make it into a Git repo or install the Git tools. Certain CI environments also lack Git sometimes. Commands that examine Git diffs aren't going to work, but everything else should. We test this somewhat regularly, but not enough, so it does get broken. If so please open an issue.

**Comment by vman** [comment]
Thanks for response @octogonz , yes I was more interested in the "rush build" command detecting the changes in the "library" packages and updating the relevant consumer packages. That doesn't seem to be possible without it being a git repo. Just wanted to confirm whether this was by design and looks like it is. Not a problem for me at this time.

**Comment by octogonz** [comment]
FYI this was a performance optimization: we tried caluclating file hashes using JavaScript but it was very slow. Whereas Git already has these hashes precomputed by native code and cached, so it's much faster. So we could remove the Git requirement, but it might be a bad experience
