### ISSUE TITLE
[api-extractor] Setting message.handled does not increment error/warning count

### ISSUE THREAD

**Issue by skaapgif** [Microsoft/web-build-tools#1258]
As per the documentation, I expect the error/warning count to increment even if `message.handled` is set to true:
> If handled is set to true, the message will still be included in the count of errors/warnings; to discard a message entirely, instead assign logLevel = none

Setting `message.handled = true` on `ConsoleMessageId.ApiReportNotCopied` results in `success: true` and 0 errors and warnings in the `ApiExtractorResult`.

Tested on 7.1.1 and 7.0.41

**Comment by octogonz** [comment]
Weird.  At first glance the code seems correct.  I'll have to debug this.

**Comment by octogonz** [comment]
Nope, it's a bug.  :-)  Here's a PR: https://github.com/Microsoft/web-build-tools/pull/1262

Thanks @skaapgif for reporting this!
