### ISSUE TITLE
[api-extractor] Need a way to suppress trimming message

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/web-build-tools#1261]
Being able to trim APIs is a handy way to clear out internal code from what the user can see externally. This gives TypeScript a bit of extra control it doesn't have by default.

Trimming a member during an api-extractor run leaves this bit in the resulting .d.ts file:

```
 Excluded from this release type: <symbol name>
```

This might be handy for testing, but it would be good to have a way to remove this comment (without having to post-process the file). This isn't something a user should see, if the functionality is used to hide parts of the API from them.

**Comment by octogonz** [comment]
These comments were originally introduced for diagnostic purposes:  When you are first enabling trimming, it's helpful for developers to understand what got trimmed.  But yeah, I can see how these comments are not useful for external consumers of a mature library, and may reveal information that was meant to be internal.  

Perhaps it should still be enabled by default (to help people who are getting started), but we can provide an **api-extractor.json** setting to opt out.

**Comment by octogonz** [comment]
Here's a PR: https://github.com/Microsoft/web-build-tools/pull/1263

**Comment by octogonz** [comment]
@jonathandturner  This feature was released with API Extractor 7.1.3.
