### ISSUE TITLE
[rush] Rush 5.7 + PNPM 3.0 does fails to fetch packages in VSTS

### ISSUE THREAD

**Issue by christiango** [microsoft/web-build-tools#1274]
A few teams in Office have been trying to upgrade to Rush 5.7 with PNPM 3.2 and we haven't been able to successfully run rush update. Things work fine with rush 5.6.0 and pnpm 2.15.1. My question is has anyone gotten the latest Rush + pnpm to work for VSTS repos with private VSTS npm feeds?

The error is usually that packages that we are trying to download from the VSTS feed fail to download. Here is the output from a recent run where we also got a useful error message with ctrl + c:

WARN  Fetching office.pkgs.visualstudio.com/Fetching office.pkgs.visualstudio.com/@jest/reporters/24.7.1 failed!
 
Then, if I cancel (Ctrl + C) I get these errors:
Error: 400 Authentication information is not given in the correct format. Check the value of Authorization header.: https://office.pkgs.visualstudio.c
om/_packaging/Office/npm/registry/@ms/visio-online-icons/-/visio-online-icons-2.0.0.tgz
    at fetch (C:\Users\madosal\.rush\node-v10.15.0\pnpm-3.2.0\node_modules\pnpm\lib\node_modules\@pnpm\tarball-fetcher\lib\createDownloader.js:48:33)
    at process._tickCallback (internal/process/next_tick.js:68:7

**Comment by octogonz** [comment]
@christiango have you tested earlier versions of PNPM?  PNPM 3.1.1 is currently being used in **web-build-tools** without any known problems.  If you could pinpoint a specific version where the regression was introduced, that would be super helpful.

You could also try downgrading Rush, but to my knowledge there aren't any significant differences [between versions 5.6.0 and 5.7.1](https://github.com/microsoft/web-build-tools/blob/master/apps/rush/CHANGELOG.md).  (Well, we did enable [--resolution-strategy=fewer-dependencies](https://github.com/microsoft/web-build-tools/blob/85fbb361c3b561c1bc5b774563405a10e099158d/apps/rush-lib/assets/rush-init/rush.json#L52) by default in 5.7.0, which is a nontrivial change, but it seems pretty unrelated to authorization.)

@zkochan has anything changed with regards to authentication in PNPM 3.2 as far as you know?

**Comment by zkochan** [comment]
I don't know what caused the regression and it is hard for me to investigate because I don't have this VSTS registry. But this is a real issue because it was reported alread: https://github.com/pnpm/pnpm/issues/1815

The regression was caused by some change in pnpm v3.0.0-beta.0

**Comment by octogonz** [comment]
> I don't know what caused the regression and it is hard for me to investigate because I don't have this VSTS registry.

@zkochan Here's instructions for creating a free Azure DevOps (ADO) test account without any requirement for a credit card or phone number:

1. Create a Microsoft linked account if you don't have one already, e.g. using www.hotmail.com
2. Go to https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/ 
3. Click the button to create a free account for "Small Teams" (which includes the "Azure Artifacts" feature)
4. Create a new "private" type project
5. In the left menu, click the "Artifacts" icon
6. Click "New Feed"
7. Call it "my_feed"
8. Keep the default settings, which include "Use packages from public sources through this feed" to act as a proxy for npmjs.com
9. Click "Create"
10. Click the "Connect to feed" button
11. Choose "npm" on the left nav bar
12. Click the button that says "Generate npm credentials"

After adding this info to your .npmrc file, you should now be able to publish private packages to the ADO private feed (and install public packages via the caching proxy).

**Comment by octogonz** [comment]
@christiango BTW I noticed that your Authorization URL starts with `https://office.pkgs.visualstudio.com/`.  As I recall these URLs got changed when they renamed VSTS to ADO last fall.  Could you double-check your feed URL and make sure it's not now a `.azure.com` address?  The old URLs seem get redirected reliably as far as I know, but it's worth checking.  

Also, @iclanton have you tried upgrading any of your internal projects to use PNPM 3.x yet?

**Comment by zkochan** [comment]
@octogonz thanks for the steps! I was able to configure it.

Indeed, when I use the new URL format, the `.azure.com` one, then it works. When I use the `.visualstudio.com` format then it fails. So switching to the new URL should fix the issue. But I will investigate why it works with pnpm v2 but not with v3.

**Comment by christiango** [comment]
@octogonz, I can't seem to find any references to an azure url in any UI for azure dev ops. Where can I find out more about this URL change? Would I just replace visualstudio.com with azure.com?

**Comment by octogonz** [comment]
Did you try the instructions I posted above? That last dialog box should show the URL.

**Comment by christiango** [comment]
Yeah, I navigated to the generate npm credentials. Are all still using office.pkgs.visualstudio.com urls

**Comment by christiango** [comment]
And I checked all the big MSFT projects using Rush + PNPM, none are on PNPM 3.x and all are still using the visualstudio.com URLs. Other teams are running into the same issue.

**Comment by zkochan** [comment]
Old format: `//{organisation}.pkgs.visualstudio.com/_packaging/{project}/npm/registry/`
new format: `//pkgs.dev.azure.com/{organisation}/_packaging/{project}/npm/registry/`

My feed shows the new format but the old works as well.

**Comment by christiango** [comment]
Thanks! It does seem to work if I switch to the new URL format.

**Comment by zkochan** [comment]
I could also come up with a fix in pnpm (thanks to @aquark). Here's the PR: https://github.com/pnpm/pnpm/pull/1825

**Comment by zkochan** [comment]
:ship: [pnpm@3.3.2](https://github.com/pnpm/pnpm/releases/tag/v3.3.2)

**Comment by christiango** [comment]
Can confirm that the issue is gone with pnpm 3.3.2
