### ISSUE TITLE
rush-stack-compiler-3.4?

### ISSUE THREAD

**Issue by grhillmsft** [microsoft/web-build-tools#1275]
Hello! I am writing an SPFx application, and the new 1.8.2 framework uses a `rush-stack-compiler` npm package to select what version of Typescript is used. The latest version I see here and on npm is `rush-stack-compiler-3.3`. I would like to use Typescript 3.4 or later to take advantage of incremental compilation and generally faster build times. Is this planned any time soon? 

Thank you!

**Comment by iclanton** [comment]
Let me see what I can do.

**Comment by iclanton** [comment]
Done: www.npmjs.com/package/@microsoft/rush-stack-compiler-3.4 (it might take a little while for the NPM website to update)
