### ISSUE TITLE
[api-extractor] Incorrect handling extends tsconfig's option

### ISSUE THREAD

**Issue by timocov** [microsoft/web-build-tools#1284]
It looks like `basePath` arg for `parseJsonConfigFileContent` (`extractorConfig.projectFolder`) in https://github.com/microsoft/web-build-tools/blob/55a285ebb9b3f060fd5ad847c2cf7ac34427b3c5/apps/api-extractor/src/api/CompilerState.ts#L58-L62 should be relative to tsconfig file, not just project folder.

Let's say we have `/package/tsconfig.base.json` and `/package/src/tsconfig.json` in `/projects` folder which `extends` base config: `"extends": "../tsconfig.base.json"`. In this case we'll be an error `Error: Error parsing tsconfig.json content: The specified path does not exist: '/projects/tsconfig.base.json'.`.

Refernces: https://github.com/timocov/dts-bundle-generator/pull/83/files.

**Comment by octogonz** [comment]
Agreed. Would you want to make a PR?

**Comment by timocov** [comment]
Sure.
