### ISSUE TITLE
[ts-command-line] Documentation link is broken.

### ISSUE THREAD

**Issue by Jason-Terry** [microsoft/web-build-tools#1285]
Can not view the API documentation... Making this framework cumbersome to adapt. The examples do not clearly indicate how you would design around the framework.

**Comment by octogonz** [comment]
Which URL are you referring to?

**Comment by Jason-Terry** [comment]
Very sorry I forgot to specify.

The API Reference Link at the bottom of the page.

[API Refrence](https://rushstack.io/api/ts-command-line.html)

**Comment by octogonz** [comment]
The current URL should be: https://microsoft.github.io/web-build-tools/api/

(It was originally supposed to be moved to the rushstack.io site, but that got procrastinated until someone finds time to revisit it.)

Feel free to make a PR to update it.

**Comment by Jason-Terry** [comment]
Okay, up to date.

**Comment by octogonz** [comment]
> Okay, I submitted a file change proposal.

Hrmm...  @Jason-Terry  I cannot seem to find your PR.  I went ahead and created PR https://github.com/microsoft/web-build-tools/pull/1298
