### ISSUE TITLE
[Rush] Rush install is not respecting the shrinkwrap

### ISSUE THREAD

**Issue by christiango** [microsoft/web-build-tools#1288]
We recently upgraded to Rush 5.7.3 + pnpm 3.3.2 and starting seeing some strange behavior.

Our pnp-lock.yaml has this dependency:
      office-ui-fabric-react: 6.182.1

`rush install -p` or `rush install` where the packages aren't cached ends up installing
     office-ui-fabric-react: 6.184.1

This repo is not open source, so we are probably going to have to work with the Rush contributors at Microsoft to debug further.

**Comment by octogonz** [comment]
(FYI many of @iclanton & co are at a conference this week. I'm reachable on Gitter.)

**Comment by halfnibble** [comment]
I wonder if this is related to my issue #1289 (`rush update --full` is broken).

When was the last time you remember `rush install` installing the correct version?

**Comment by christiango** [comment]
The last time I can say it worked was pre pnpm 3

**Comment by elliottsj** [comment]
This could be related to https://github.com/microsoft/web-build-tools/issues/1142, which occurs with pnpm@2.25.6.

**Comment by octogonz** [comment]
Without repro steps, there's not much we can do here.

**Comment by christiango** [comment]
Our repo isn't open source, so we're waiting for someone from Microsoft to reply to our internal thread once @iclanton and co are back.

In parallel, we are exploring moving to yarn to see if we see more stability there going forward.

**Comment by octogonz** [comment]
@christiango BTW did you take a look at https://github.com/microsoft/web-build-tools/issues/1273#issuecomment-492779995 ?  The PNPM lockfile is not intended to be an exact installation plan.

**Comment by christiango** [comment]
I hadnt seen that, thanks for sharing. When did this design change come?

Non deterministic npm installs for us on Office Online is a deal breaker.

**Comment by octogonz** [comment]
> Non deterministic npm installs for us on Office Online is a deal breaker.

The installation /is/ deterministic.  But it's a deterministic function of the Git commit (i.e. **package.json** files and shrinkwrap), not the shrinkwrap alone.

**Comment by acoates-ms** [comment]
Maybe checkout the repo in #1142? I think that is also basically the shrinkwrap not working, and that one has a non-internal repro attached

**Comment by christiango** [comment]
Do you have to combination of Rush/pnpm that last has the "old" behavior?

We want the updates of packages to be intentional, and we were seeing things like fabric react getting updated due to something seemingly unrelated. Do other package managers for mono repos have the same behavior? 

This behavior resulted in 2 bad regressions for us in the 4 day period we were on the latest version of Rush, so I would like to understand more of the background of this change

**Comment by octogonz** [comment]
I haven't had a chance to look at @acoates-ms 's repro yet. I'll see if I can do that asap. Also Ian is back in town and said he would follow up regarding your internal repro. Installation behaviors tend to be complex, so we should avoid speculating what the issue is until we've had a chance to debug an actual repro. The shrinkwrap optimization I described has been around since Rush 5 if I remember right, so maybe this is something new.

**Comment by octogonz** [comment]
I updated #1142 with more info.  Let's continue the discussion there for now.

**Comment by octogonz** [comment]
> Do you have to combination of Rush/pnpm that last has the "old" behavior?

The shrinkwrap optimization was introduced with Rush 5 (see commit e54de733841350d6ab27f02d1815c0b9ffa68672).  So it's been around a long time.

**Comment by sachinjoseph** [comment]
I just closed #1142. @christiango Can you verify if you can still repro this issue on Rush 5.10.0 and PNPM 3.5.3?

**Comment by christiango** [comment]
On vacation,  will confirm in 2 weeks when I am back. Thanks for driving a fix!

**Comment by rakeshpatnaik** [comment]
@christiango - Can you please look into it?

**Comment by christiango** [comment]
Someone on our team is currently working on trying to get us on the latest rush + pnpm. We'll confirm sometime next week if the issue is gone, since it doesn't appear until new versions of packages are published to the feed after we've updated the shrinkwrap.

**Comment by octogonz** [comment]
Thanks! It bugs me that this thread was open for so long. Reliability is super important for Rush. It sounds like we've sorted it out, but if there are any remaining known issues, we should prioritize getting them fixed, or issue a warning if the latest PNPM has a known incompatibility.

**Comment by christiango** [comment]
We havent seen this issue in 2 days after upgrading to the latest.
