### ISSUE TITLE
[rush] "rush update --full" is broken

### ISSUE THREAD

**Issue by halfnibble** [microsoft/web-build-tools#1289]
When I run `rush update --full` on the web-build-tools repo, it removes the file `common/config/rush/pnpm-lock.yaml`, which I believe is intended. However, it does not recreate the file.

Furthermore, running `rush update` will no longer update the file. It is just gone for good. I can't figure out how to get it back either.

**Comment by halfnibble** [comment]
Could this undefined return be the source of the issue?
https://github.com/microsoft/web-build-tools/blob/master/apps/rush-lib/src/logic/pnpm/PnpmShrinkwrapFile.ts#L130

**Comment by octogonz** [comment]
@halfnibble  I'm not able to repro this.  Here's what I did:

1. Clone the latest WBT master (SHA c879dda80bc0ea43a731ee7e383aeab922d6328c)
2. Run `rush update --full`

After the operation completes, I see that **common/config/rush/pnpm-lock.yaml** has some modifications, as expected.  This file was not deleted.

I used a Windows PC with Node v8.15.0.

**Comment by halfnibble** [comment]
Odd. I was able to repro with Node v8.15.0 on a Mac.

Steps:
`$ nvm install 8.15.0`
`$ nvm use 8.15.0`
`$ npm install -g @microsoft/rush`  # Installs 5.7.3
`$ git clone https://github.com/microsoft/web-build-tools/`
`$ cd web-build-tools`
`$ rush update --full`
```
$ git status
[deleted]  common/config/rush/pnpm-lock.yaml
```
And nothing seems to make the pnpm-lock.yaml file come back.

**Comment by halfnibble** [comment]
OMG. User error.
(New computer that came with `package-lock=false` already populated in `.npmrc`).
Sorry for the trouble.

**Comment by octogonz** [comment]
Was that in your user home directory? If that is taking precedence over the repo configuration, perhaps Rush should check this and issue a warning.

**Comment by halfnibble** [comment]
Yep. It was in my user home directory `~/.npmrc`. And I don't remember adding it either. I just got this new computer on Thursday, so I'm trying to retrace all my steps and figure out when that config setting was added.

**Comment by octogonz** [comment]
That seems like a pretty confusing experience. If you think it's likely that others might encounter it (and not just a random fluke), feel free to open a separate issue proposing to check for this case and report a warning.
