### ISSUE TITLE
rush rebuild -q Error: spawn ENAMETOOLONG

### ISSUE THREAD

**Issue by gmareater** [Microsoft/web-build-tools#130]
hi 
I'm using rush for angular2 - webpack (https://github.com/AngularClass/angular2-webpack-starter)

rush generate 
and
rush link
throw no error
but 
rush rebuild -q
```

> Starting task [components]
> Starting task [elearning]
internal/child_process.js:313
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENAMETOOLONG
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:380:9)
    at Object.exports.execFile (child_process.js:143:15)
    at Object.exports.exec (child_process.js:103:18)
    at C:\Users\admin\AppData\Roaming\npm\node_modules\@microsoft\rush\node_modules\@microsoft\package-deps-hash\lib\get
PackageDeps.js:45:35
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
```

**Comment by pgonzal** [comment]
Hi @gmareater, I apologize no one has followed up on your issue.  If you can provide a repro (e.g. git branch that I can clone), I'd be happy to investigate.  Thanks!

**Comment by nickpape-msft** [comment]
From the callstack is looks like it may be an issue with package-deps attempting to pull git hashes for incremental builds.

**Comment by gmareater** [comment]
hi 
it's really a clone of this git: ( with almost no change)
https://github.com/AngularClass/angular2-webpack-starter

I have five of them in different folders.
 with this structure (red line are the cloned one)
![image](https://cloud.githubusercontent.com/assets/6206777/24837256/235c3e56-1d45-11e7-95a9-25b287bd8580.png)

**Comment by pgonzal** [comment]
Can you share your `rush.json` configuration? i.e. something I can try to build to reproduce the error?

**Comment by qz2017** [comment]
closing old issue.. @gmareater , feel free to reopen it with information about your rush.json.
