### ISSUE TITLE
[rush] Dependency on js-yaml@3.9.1 which has a high vulnerability

### ISSUE THREAD

**Issue by labbruzzesi** [microsoft/web-build-tools#1302]
My organization has a central node package repository, and there is a prohibition on installing packages with high vulnerabilities in their dependency tree.  @microsoft/rush-lib currently directly depends on js-yaml@3.9.1 which has a high vulnerability.  This vulnerability was resolved in js-yaml@3.13.1.  This package should use the latest version of js-yaml to remove the vulnerability.

**Comment by octogonz** [comment]
This should be a simple upgrade.

**Comment by octogonz** [comment]
@labbruzzesi as far as I can tell, Rush was already upgraded to js-yaml@3.13.1.  Are you using the latest version?  From the history it looks like that fix got published with Rush 5.7.2.

**Comment by rakeshpatnaik** [comment]
This has been verified that vulnerability has been removed as of Rush 5.10.0.

**Comment by rakeshpatnaik** [comment]
Correc
