### ISSUE TITLE
[rush] Not linking devDependencies?

### ISSUE THREAD

**Issue by Sushisource** [microsoft/web-build-tools#1333]
Hello, really like the tool!

Just recently started using webpack in one package in my monorepo, added webpack and a variety of plugins as devDependencies, but for some reason (and consistently) rush will indeed download the deps and put them in the `common` folder, but fails to link them into the package's `node_modules` when I `rush update` or `rush install` -- unless I `rush purge` first.

This is with yarn 1.16.0 as my package manager, and rush 5.9.0.

I could've sworn this used to work (haven't touched this part of our code in a while).

Happy to provide any logs / other info to assist with debugging.

**Comment by octogonz** [comment]
The version range in your `devDependencies` needs to be SemVer compatible with the `version` field in the **package.json** file for your local project.  Let us know if that solves your issue.

(BTW we recognize that this requirement could be more intuitive.  Issue https://github.com/microsoft/web-build-tools/issues/547 proposes a possible improvement.)

**Comment by Sushisource** [comment]
@octogonz Yup, that was it. The proposed solution would definitely help. Thanks for the info.
