### ISSUE TITLE
[rush] "rush update" is broken with pnpm 3.5.3+

### ISSUE THREAD

**Issue by sachinjoseph** [microsoft/web-build-tools#1339]
**pnpm install** will no longer upgrade dependency versions, which means neither **rush install** nor **rush update** will upgrade dependency versions any longer.

**rush update** currently calls **pnpm install** internally. This needs to be changed to **pnpm update**.

See:
1. https://github.com/microsoft/web-build-tools/issues/1142#issuecomment-504933845
2. https://github.com/pnpm/pnpm/issues/1876

**Comment by sachinjoseph** [comment]
PR https://github.com/microsoft/web-build-tools/pull/1340 partially addresses this issue. Specifically the `rush update --full` scenario is addressed.

**Comment by octogonz** [comment]
This should be a fairly easy fix, right? If the PNPM version is newer than a certain version, then run `pnpm update` instead of `pnpm install`, right?

**Comment by sachinjoseph** [comment]
Yes, you are right.

**Comment by sachinjoseph** [comment]
On the other hand, I think we might not need **pnpm update** at all, at least on versions 3.5.3+:

| Command &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; | current internal pnpm command | proposed internal pnpm command | Remarks
| --- | --- | --- | --- |
| **rush install** | **pnpm install --no-prefer-frozen-lockfile* | **pnpm install --frozen-lockfile** | Uses the shrinkwrap as is, fails if it needs an update. Blocked by https://github.com/pnpm/pnpm/issues/1882 and https://github.com/pnpm/pnpm/issues/1889 |
| **rush update** | **pnpm install --no-prefer-frozen-lockfile** | **pnpm install** | Based on https://github.com/pnpm/pnpm/issues/1876. This discussion is not over yet but I think it is safe to go with **pnpm install** for **rush update**. |
| **rush update --full** | **pnpm install --no-prefer-frozen-lockfile** | **pnpm install** | Rush deletes the existing pnpm-lock.yaml (and its copy maintained internally, see https://github.com/microsoft/web-build-tools/pull/1340) and so **pnpm install** would be equivalent to a **pnpm update**. |

What do you think?

I am making an assumption here that **pnpm update** is equivalent to **pnpm install** in the absence of a shrinkwrap file. Let me know if this is inaccurate.

**Comment by sachinjoseph** [comment]
Continuing the discussion here https://github.com/pnpm/pnpm/issues/1890

**Comment by sachinjoseph** [comment]
Continuing the discussion here https://github.com/microsoft/web-build-tools/issues/1142

**Comment by octogonz** [comment]
Thanks for your hard work on this important issue @sachinjoseph

**Comment by sachinjoseph** [comment]
Thank you @octogonz for your continued insights and suggestions :-) I was going through your previous explanations on various GitHub issues to understand everything about Rush and pnpm and how they work together.

**Comment by sachinjoseph** [comment]
Closing this issue as Rush release 5.10.0 has addressed this.
