### ISSUE TITLE
[rush] "rush change" should give a clearer message when a changefile is unnecessary

### ISSUE THREAD

**Issue by KRyan** [microsoft/web-build-tools#1344]
Scenario: I'm accustomed to running 'rush change' before every PR, but my change happens to be in a package which is not managed by rush, so rush change is unnecessary.  But when I hit this scenario, it took me time to realize this was by design. 

The message it gives is:
> Rush Multi-Project Build Tool 5.9.1 - https://rushjs.io
> 
> Starting "rush change"
> 
> The target branch is origin/master
> No changes were detected on this branch. Nothing to do.

I suggest changing the last phrase to something like "No changes were detected **to relevant packages** on this branch. Nothing to do."

**Comment by octogonz** [comment]
Sounds good. Feel free to create a PR.
