### ISSUE TITLE
[rush] How to debug custom command?

### ISSUE THREAD

**Issue by GongT** [microsoft/web-build-tools#1348]
I have a custom bulk command "upgrade" in `command-line.json`. It will run my custom script "upgrade" in `package.json` for each project.

But when I run `rush upgrade`, it hangs up. I can not know what's going wrong. There is no log files like the "build" command, and I can not find a option like "verbose".

So how can I see what's happening?

(I tried `yarn run upgrade` in each folder, it works)

**Comment by iclanton** [comment]
Which version of Rush are you using? If you run `rush upgrade -h`, what help messages do you get? 
Your `upgrade` command is a bulk action, right? What does your `command-line.json` look like?

There is a `--verbose` parameter for every bulk script action (see [here](https://github.com/microsoft/web-build-tools/blob/5aff38fd61af71ac7a83205829650f0a069bc1b2/apps/rush-lib/src/cli/scriptActions/BulkScriptAction.ts#L161-L165)), so supplying a `--verbose` parameter should print the messages that your command prints.

**Comment by GongT** [comment]
Ok, it works, I tried to find help from "rush -h upgrade".

I found my command is wrong with it output, thanks.
