### ISSUE TITLE
[Rush] Build fails with multiple version of Office UI Fabric

### ISSUE THREAD

**Issue by HarryGifford** [microsoft/web-build-tools#1351]
I have two projects, one of which uses a React 15 based Office UI Fabric and another which uses a React 16 based version. When I try to maintain them together in the same Rush monorepo, the build fails.

Is this a known issue and is there a work around?

[RushWithMultipleFabricVersions](https://github.com/HarryGifford/RushWithMultipleFabricVersions) is a simple repro of this issue.

**Comment by iclanton** [comment]
Interesting issue. We'll check out your repro.

**Comment by octogonz** [comment]
I believe this is a bug in OUIFR itself.  The `@uifabric/utilities` package has a [phantom dependency](https://rushjs.io/pages/advanced/phantom_deps/) on `@types/react`:

**package.json**
```js
{
  "name": "@uifabric/utilities",
  "version": "5.34.2",
  "description": "Office UI Fabric utilities for building React components.",
  "main": "lib/index.js",
  "typings": "lib-es2015/index.d.ts",
  "sideEffects": false,
  "repository": {
    "type": "git",
    "url": "https://github.com/OfficeDev/office-ui-fabric-react"
  },
  "license": "MIT",
  "scripts": {
    "build": "node ../../scripts/build.js",
    "clean": "node ../../scripts/clean.js",
    "start-test": "node ../../scripts/start-test.js"
  },
  "disabledTasks": [
    "copy",
    "karma",
    "webpack"
  ],
  "devDependencies": {
    "@types/jest": "21.1.8",
    "@types/enzyme": "3.1.5",
    "@types/enzyme-adapter-react-16": "1.0.1",
    "@types/prop-types": "15.5.2",
    "@types/react": "16.3.13",    <=== INCORRECT; NEEDS TO BE A PEER
    "@types/react-dom": "16.0.5",
    "@types/sinon": "2.2.2",
    "enzyme": "^3.2.0",
    "enzyme-adapter-react-16": "^1.1.0",
    "office-ui-fabric-react-tslint": ">=5.0.0 <6.0.0",
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "sinon": "^4.1.3"
  },
  "dependencies": {
    "@uifabric/merge-styles": ">=5.17.1 <6.0.0",
    "prop-types": "^15.5.10",
    "tslib": "^1.7.1"
  },
  "peerDependencies": {
    "react": "^0.14.9 || ^15.0.1-0 || ^16.0.0-0",    <=== CORRECT
    "react-dom": "^0.14.9 || ^15.0.1-0 || ^16.0.0-0"
  }
}
```

Thus this package likely to malfunction in a side-by-side installation.

You might be able to hack around it in **pnpmfile.js**, but the correct solution is to fix the OUIFR dependencies.

(BTW if you are merely wanting to build an application that can be built for React 15 or 16, Rush's [installation variantes](https://rushjs.io/pages/advanced/installation_variants/) feature provides a way to maintain two different shrinkwrap files, without having to do side-by-side.)

**Comment by HarryGifford** [comment]
Thank you for investigating this @octogonz. I've opened an issue on the office-ui-fabric-react page.

In our case we have components which are using different versions of the office-ui-fabric. I will try modifying `pnpmfile.js` in the mean time.
