### ISSUE TITLE
[api-extractor] Error: Symbol not found for identifier: WebAssembly

### ISSUE THREAD

**Issue by bitjson** [microsoft/web-build-tools#1370]
May be related to #1304 – I'm trying:

```
bitcoin-ts $ yarn
bitcoin-ts $ yarn build
bitcoin-ts $ api-extractor run --local --verbose

api-extractor 7.3.0  - https://api-extractor.com/

Using configuration from /[...]/bitcoin-ts/api-extractor.json

Error: Symbol not found for identifier: WebAssembly
```

The repo is [bitauth/bitcoin-ts](https://github.com/bitauth/bitcoin-ts), and the only non-default configuration is: `"mainEntryPointFilePath": "<projectFolder>/build/main/index.d.ts",`.

Any ideas for how to correct this? Thanks!

**Comment by iclanton** [comment]
Do you have the typings for WebAssembly referenced in your `tsconfig.json`?

**Comment by bitjson** [comment]
@iclanton thanks for the quick response. Yes –`"lib"` is currently set to `[
      "es2017",
      "esnext.bigint",
      "dom"
    ]`, and the WebAssembly namespace is now in `lib.dom.d.ts`. (A recent development – previously separate in [@types/webassembly-js-api](https://www.npmjs.com/package/@types/webassembly-js-api).)

**Comment by octogonz** [comment]
> Is there a better way to generate debug logs or a more verbose error message?

Yes, you can do `api-extractor run --local --diagnostics`.

> `Error: Symbol not found for identifier: WebAssembly`

I cannot repro this error.  I did this:
1. Clone https://github.com/bitauth/bitcoin-ts/commit/cd8f44d639348d5f3917f7cf78b6e35f8c1b28ce
2. Run `api-extractor init` using 7.3.0
3. Edit `mainEntryPointFilePath` as you said.
4. Run `api-extractor run --local --diagnostics`

It generated the rollup and API report just fine.  I am using NodeJS 10.13.0 on Windows 10.

@bitjson could you provide more specific repro steps?

**Comment by bitjson** [comment]
Ah, very sorry, I thought I had also reproduced the issue on the `master` branch. I just pushed an [`api-extractor` branch](https://github.com/bitauth/bitcoin-ts/tree/api-extractor) where I'm getting the error. Thanks for your help!

**Comment by bitjson** [comment]
Ok, after trying the `--diagnostics` flag, the issue is definitely that it's using the version of `lib.dom.d.ts` from typescript `v3.4.5` (`node_modules/@microsoft/api-extractor/node_modules/typescript/lib/lib.dom.d.ts`), but my project is build with that from `3.5.3` (`node_modules/typescript/lib/lib.dom.d.ts`).

 I see some [info in the documentation about `IExtractorInvokeOptions.typescriptCompilerFolder`](https://api-extractor.com/pages/setup/invoking/). That sounds like what I need to adjust, but I'm not sure if I understand how – can that be set in `api-extractor.json`? (I don't see it [in the schema](https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json).)

**Comment by octogonz** [comment]
> Ok, after trying the `--diagnostics` flag, the issue is definitely that it's using the version of `lib.dom.d.ts` from typescript `v3.4.5`

Awesome!  PR https://github.com/microsoft/web-build-tools/pull/1359 paid off after just a few days.  :-D

**Comment by octogonz** [comment]
> The `WebAssembly` namespace was added to `lib.dom.d.ts` in [microsoft/TypeScript@1e7482a](https://github.com/microsoft/TypeScript/commit/1e7482ad05034fd92254bf4a5119a895f64e89e3), which didn't get released until `v3.5.1`.

The right fix is for us to upgrade API Extractor's TypeScript compiler.


> I see some [info in the documentation about `IExtractorInvokeOptions.typescriptCompilerFolder`](https://api-extractor.com/pages/setup/invoking/). That sounds like what I need to adjust, but I'm not sure if I understand how – can that be set in `api-extractor.json`?

It's a command-line option `--typescript-compiler-folder`.   You can use that as a workaround.

**Comment by octogonz** [comment]
Here's a PR: https://github.com/microsoft/web-build-tools/pull/1372

**Comment by bitjson** [comment]
@octogonz not sure how I didn't realize it was a CLI option – working well now, thanks! (And thanks for the fantastic project! Looking forward to building out my documentation with this.)
