### ISSUE TITLE
[rush] `Rush install` fails with Rush 5.10.1 and pnpm 3.5.3

### ISSUE THREAD

**Issue by calebmshafer** [microsoft/web-build-tools#1392]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

Updating to Rush 5.10.1 and pnpm 3.5.3 from pnpm 2.25.7, I can now successfully `rush update` (thanks to #1347).  However, when I try to run a `rush install` it fails saying `The shrinkwrap is missing the following dependencies:`.  A subsequent `rush update` will work though.

The workflow I followed is:
1. Update rush.json
1. Delete existing `shrinkwrap.yaml`
    - `common\temp` did not exist either
1. Run `node common/scripts/install-run-rush.js update --full`.  Which succeeds and appears to work properly
    - Same issue if `rush update` instead of `--full` is run here.
1. Run `node common/scripts/install-run-rush.js install`.  This fails with the shrinkwrap is missing dependencies error.

There is a repro repo here, https://github.com/calebmshafer/imodeljs_rush_bug_repro.

**What is the expected behavior?**

I expected `rush update` to create the pnpm-lock.yaml file correctly so `rush install` works after the lock file is initially created.

**Please provide the tool version, Node.js version and OS.**

* Tool: Rush
* Tool Version: 
* Node Version: 10.15.3
* OS: Windows 10 1809

**Comment by sachinjoseph** [comment]
I can repro this. Looking into this.

**Comment by sachinjoseph** [comment]
#1393

**Comment by calebmshafer** [comment]
I can confirm Rush 5.10.3 is now working with pnpm 3.5.3 for our repo.  Thanks!!
