### ISSUE TITLE
[rush] "rush update" error when adding new project to rush.json

### ISSUE THREAD

**Issue by ScottHysom** [microsoft/web-build-tools#1418]
**Is this a feature or a bug?**

- [ ] Feature
- [X] Bug

**Please describe the actual behavior.**
With rush version 5.10.3 and pnpm version 3.6.0, users can no longer add a new project to their `rush.json` and run `rush update`. Instead, `rush update` results in this error:

`ERROR: Cannot get dependency key for temp project: @rush-temp/new-project`

A simple repro can be found at https://github.com/ScottHysom/rush-issue-add-project. See the README.md for simple repro steps.

To work around this issue, a user must manually change the `pnpm-lock.yaml` and add the following line under the top `dependencies` key:

`'@rush-temp/new-project': 'file:path-to-project/new-project.tgz'`

**What is the expected behavior?**
`rush update` succeeds in updating the pnpm lock file without manual intervention.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** rush
* **Tool Version:** 5.10.3
* **pnpm Version:** 3.6.0
* **Node Version:** 10.14.1
  * **Is this a LTS version?** Yes
  * **Have you tested on a LTS version?** Yes
* **OS:** Windows 10 version 1903

**Comment by iclanton** [comment]
@sachinjoseph, this looks like a regression from one of your recent PNPM bugfixes. Can you take a look at this?

**Comment by sachinjoseph** [comment]
Looking into it

**Comment by sachinjoseph** [comment]
https://github.com/microsoft/web-build-tools/pull/1422

**Comment by sachinjoseph** [comment]
@ScottHysom Can you verify with Rush 5.11.0?

**Comment by ScottHysom** [comment]
I have confirmed this issue has been resolved with 5.11.0. Thanks!
