### ISSUE TITLE
[rush] Critical path computation is broken 

### ISSUE THREAD

**Issue by nayanshah** [microsoft/web-build-tools#1423]
**Is this a feature or a bug?**

- [ ] Feature
- [*] Bug

**Please describe the actual behavior.**

Projects not on the critical path could be built before ones that are on it. TaskRunner attempts to compute critical paths based on project dependencies but this is incorrect.

[TaskRunner.ts](https://github.com/microsoft/web-build-tools/blame/master/apps/rush-lib/src/logic/taskRunner/TaskRunner.ts#L373)

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

**What is the expected behavior?**

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** 
* **Tool Version:** 
* **Node Version:** 
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS:**

**Comment by iclanton** [comment]
Thanks for catching this! The fix is merged in.
