### ISSUE TITLE
[rush] install-run.js doesn't respect RUSH_TEMP_FOLDER

### ISSUE THREAD

**Issue by wolfd** [microsoft/web-build-tools#1431]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**Please describe the actual behavior.**
This is sort-of a feature, but for me it acts more like a bug.

running `install-run-rush.js` with `RUSH_TEMP_FOLDER` set installs rush into `common/temp` and then runs rush, which then respects `RUSH_TEMP_FOLDER`. The rush executable works, and rush's installs work, but the directories are different.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Setting `RUSH_TEMP_FOLDER` to any other directory, and then running `install-run.js`.
Personally, I'm having trouble because I'm using `install-run-rush.js` to run rush, which installs rush into the wrong temp folder, and then starts respecting the environment variable.

In `common/scripts/install-run.js`:
`const rushTempFolder = ensureAndJoinPath(rushCommonFolder, 'temp');`
and
`const packageInstallFolder = ensureAndJoinPath(rushCommonFolder, 'temp', ...`
are to blame here.

**What is the expected behavior?**

I'd expect `install-run.js` to respect `RUSH_TEMP_FOLDER`.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** rush
* **Tool Version:** 5.10.3
* **Node Version:** (shouldn't be relevant, things are working)
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** 
* **OS:** Ubuntu 16.04

**Comment by octogonz** [comment]
This is arguably a bug.  `install-run-rush.js` should honor `RUSH_TEMP_FOLDER`.

**Comment by nayanshah** [comment]
@octogonz install-run-rush also ignores `RUSH_PREVIEW_VERSION`. Logging a separate issue for that.
