### ISSUE TITLE
[rush] Command names should allow numbers (such as 'test-e2e')

### ISSUE THREAD

**Issue by gregjacobs** [microsoft/web-build-tools#1443]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [X] Bug

**Please describe the actual behavior.**

It seems we can't have a number in a Rush command name. I'm trying to use the names 'build-e2e' and 'test-e2e', but this doesn't pass the regular expression validation.

I'm not sure that there would be a reason to not allow a number in the command names, perhaps as long as it's not the first character. Thoughts?

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Add a command to `command-line.json` named "test-e2e". This will produce the error:

```
ERROR: Invalid action name "test-e2e". The name must be comprised of lower-case words optionally separated by hyphens or colons.
```

**What is the expected behavior?**

Rush should allow numbers in command names to support command names like 'build-e2e' and 'test-e2e'

## Potential Solution

Replace the following regex:

```ts
private static _actionNameRegExp: RegExp = /^[a-z]+([-:][a-z]+)*$/;
```

with:

```ts
private static _actionNameRegExp: RegExp = /^[a-z][a-z0-9]*([-:][a-z0-9]+)*$/;
```

This will allow numbers except for the first character.

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** Rush
* **Tool Version:** 5.11.1
* **Node Version:** 10.5.1
  * **Is this a LTS version?** No
  * **Have you tested on a LTS version?** No
* **OS:** Windows 7

**Comment by octogonz** [comment]
Duhh... I am not sure why we left out the numbers.  😆

This one needs to be fixed, too:

https://github.com/microsoft/web-build-tools/blob/037c4ba527c13c8b6df4c9ddb2510dd0d137b469/libraries/ts-command-line/src/CommandLineAction.ts#L46

**Comment by gregjacobs** [comment]
Hey @octogonz, @apostolisms, sorry for the late reply on this. Thanks so much for fixing!
