### ISSUE TITLE
[api-extractor] Invalid types being generated when using barred o and export aliases

### ISSUE THREAD

**Issue by alan-agius4** [microsoft/web-build-tools#1471]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**
When having an exported class with a name prefixed with a barred o `ɵ` and is also exported using an alias invalid rolled up typings are being generated.

**Input**
```ts
export declare class ɵNgNoValidate {}
export {ɵNgNoValidate as NgNoValidate__0}
```

**Output**
```ts

declare class "ɵNgNoValidate" { }
export { "ɵNgNoValidate" as NgNoValidate__0 }
export { "ɵNgNoValidate" as ɵNgNoValidate }
export { }
```

**What is the expected behavior?**
Correct output.

```ts
declare class ɵNgNoValidate { }
export { ɵNgNoValidate as NgNoValidate__0 }
export { ɵNgNoValidate }
export { }
```
**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** @microsoft/api-extractor
* **Tool Version:** 7.3.8
* **Node Version:** 12.6.0
  * **Is this a LTS version?** 
  * **Have you tested on a LTS version?** No
* **OS:** Mojave

**Comment by alan-agius4** [comment]
//cc @octogonz, this used to work in 7.0

**Comment by octogonz** [comment]
@alan-agius4 Here's a PR: https://github.com/microsoft/web-build-tools/issues/1471

**Comment by alan-agius4** [comment]
Thanks @pgonzal for this.

Ps: I think you meant https://github.com/microsoft/web-build-tools/pull/1493 :)
