### ISSUE TITLE
[api-extractor] bundled typedef only contains index

### ISSUE THREAD

**Issue by ssube** [microsoft/web-build-tools#1486]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

`api-extractor` claims to succeed, but the resulting bundled `.d.ts` is almost identical to the input `index.d.ts`:

```shell
> /home/ssube/code/ssube/noicejs//node_modules/.bin/api-extractor run --config /home/ssube/code/ssube/noicejs//config/api-extractor.json --local -v
                                                     
api-extractor 7.3.8  - https://api-extractor.com/                                         
                          
Found metadata in /home/ssube/code/ssube/noicejs/out/tsdoc-metadata.json                                           
Writing: /home/ssube/code/ssube/noicejs/temp/noicejs.api.json
The API report is up to date: out/tmp/noicejs.api.md      
Writing package typings: /home/ssube/code/ssube/noicejs/out/noicejs-public.d.ts
Writing package typings: /home/ssube/code/ssube/noicejs/out/noicejs-beta.d.ts                                     
Writing package typings: /home/ssube/code/ssube/noicejs/out/noicejs.d.ts                                                                          
                                                                                                                       
API Extractor completed successfully
```

<details><summary>With this <code>config/api-extractor.json</code> config:</summary>
<p>

```json
{
  "$schema": "https://developer.microsoft.com/json-schemas/api-extractor/v7/api-extractor.schema.json",
  "projectFolder": "..",
  "mainEntryPointFilePath": "../out/src/index.d.ts",
  "apiReport": {
    "enabled": true,
    "reportFolder": "<projectFolder>/out/",
    "reportTempFolder": "<projectFolder>/out/tmp/"
  },
  "docModel": {
    "enabled": true
  },

  "dtsRollup": {
    "enabled": true,
    "untrimmedFilePath": "<projectFolder>/out/noicejs.d.ts",
    "betaTrimmedFilePath": "<projectFolder>/out/noicejs-beta.d.ts",
    "publicTrimmedFilePath": "<projectFolder>/out/noicejs-public.d.ts"
  },

  "tsdocMetadata": {
  },

  "messages": {
    "compilerMessageReporting": {
      "default": {
        "logLevel": "warning"
      }
    },

    "extractorMessageReporting": {
      "default": {
        "logLevel": "warning"
      }
    },
    "tsdocMessageReporting": {
      "default": {
        "logLevel": "warning"
      }
    }
  }
}
```

</p>
</details>

<details><summary>With this input <code>out/src/index.d.ts</code>:</summary>
<p>

```typescript
export { BaseOptions, Container, Contract, Constructor } from 'src/Container';
export { BaseError } from 'src/error/BaseError';
export { ContainerBoundError } from 'src/error/ContainerBoundError';
export { ContainerNotBoundError } from 'src/error/ContainerNotBoundError';
export { MissingValueError } from 'src/error/MissingValueError';
export { getInject, Inject } from 'src/Inject';
export { ConsoleLogger } from 'src/logger/ConsoleLogger';
export { Logger, LogLevel, logWithLevel } from 'src/logger/Logger';
export { NullLogger } from 'src/logger/NullLogger';
export { Module, ModuleOptions, Provider, ProviderType } from 'src/Module';
export { getProvides, Provides } from 'src/Provides';
```

</p>
</details>

<details><summary>Produces this untrimmed <code>out/noicejs.d.ts</code>:</summary>
<p>

```typescript
import { BaseError } from 'src/error/BaseError';
import { BaseOptions } from 'src/Container';
import { ConsoleLogger } from 'src/logger/ConsoleLogger';
import { Constructor } from 'src/Container';
import { Container } from 'src/Container';
import { ContainerBoundError } from 'src/error/ContainerBoundError';
import { ContainerNotBoundError } from 'src/error/ContainerNotBoundError';
import { Contract } from 'src/Container';
import { getInject } from 'src/Inject';
import { getProvides } from 'src/Provides';
import { Inject } from 'src/Inject';
import { Logger } from 'src/logger/Logger';
import { LogLevel } from 'src/logger/Logger';
import { logWithLevel } from 'src/logger/Logger';
import { MissingValueError } from 'src/error/MissingValueError';
import { Module } from 'src/Module';
import { ModuleOptions } from 'src/Module';
import { NullLogger } from 'src/logger/NullLogger';
import { Provider } from 'src/Module';
import { ProviderType } from 'src/Module';
import { Provides } from 'src/Provides';
export { BaseError }
export { BaseOptions }
export { ConsoleLogger }
export { Constructor }
export { Container }
export { ContainerBoundError }
export { ContainerNotBoundError }
export { Contract }
export { getInject }
export { getProvides }
export { Inject }
export { Logger }
export { LogLevel }
export { logWithLevel }
export { MissingValueError }
export { Module }
export { ModuleOptions }
export { NullLogger }
export { Provider }
export { ProviderType }
export { Provides }

export { }
```

</p>
</details>

Each `export { more, than, one, thing }` is being replaced with individual imports and re-exports, but are still imported from the `src/` file rather than being rolled up. When imported elsewhere, these typedefs result in path errors like:

```
ERROR in [at-loader] ./node_modules/noicejs/out/noicejs.d.ts:8:26 
    TS2307: Cannot find module 'src/Container'.

ERROR in [at-loader] ./node_modules/noicejs/out/noicejs.d.ts:9:27 
    TS2307: Cannot find module 'src/Inject'.

ERROR in [at-loader] ./node_modules/noicejs/out/noicejs.d.ts:10:29
    TS2307: Cannot find module 'src/Provides'.
```

The untrimmed, beta, and public typedefs are all identical. Adding `@public` to symbols doesn't appear to help.

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

I have a branch that should demonstrate the behavior here: https://github.com/ssube/noicejs/tree/feat/47-rollup

`make` to build (expects and runs `yarn`).

**What is the expected behavior?**

I'm expecting an `out/noicejs.d.ts` with each `out/src/**/*.d.ts` file referenced by `out/src/index.d.ts` to be included inline. For example, `out/src/error/BaseError.d.ts` should contain:

```typescript
export declare class BaseError extends Error {
    message: string;
    stack?: string;
    protected nested: Array<Error>;
    constructor(message: string, ...nested: Array<Error>);
    cause(): Error | undefined;
    readonly length: number;
}
//# sourceMappingURL=BaseError.d.ts.map
```

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** `api-extractor`
* **Tool Version:** `api-extractor 7.3.8  - https://api-extractor.com/`
* **Node Version:** `v12.9.0` (yarn `v1.17.3`)
  * **Is this a LTS version?** no (but it will be soon)
  * **Have you tested on a LTS version?** no
* **OS:** `Linux cerberus 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by octogonz** [comment]
The TypeScript input looks like it has syntax errors in it. For example, the import path must be `"./src/Container"`. When you write `"src/Container"` it means to import from an NPM package named `src`. 

Thanks for the repro branch. When I get some time I'll clone it and see if I can give more specific advice.

**Comment by ssube** [comment]
Good point. :thinking:  With my previous webpack config, `src/` and `test/` were explicitly defined as aliases to the directories of the same name. When I moved to rollup, those are no longer in the config, but have continued working and I never thought twice about it.

**Comment by octogonz** [comment]
Also when I run `tsc` your compiler outputs are being written under the `src` input folder.  

Looks like the `baseUrl` and `paths` entries in your **tsconfig.json** are causing all this trouble.  It's really not the standard way to do modern TypeScript imports.  I'm frankly impressed if the resulting .d.ts files are compiling without errors for a consumer of this library.  😊

Here's a quick hack to convert your project to use conventional imports: https://github.com/ssube/noicejs/pull/49

With this change, API Extractor works fine at least.

**Comment by ssube** [comment]
Output under the `src` folder? I'm not able to reproduce that, with a clean clone or in CI. Are you running `tsc` directly?

After running `make`, which runs `rollup` and then `tsc` via `rollup-plugin-typescript2`, the only output JS files I see are under `out/`:

```
> find . -name '*.js' | grep -v node_modules 

./out/coverage/sorter.js                            
./out/coverage/lcov-report/sorter.js                
./out/coverage/lcov-report/block-navigation.js      
./out/coverage/lcov-report/prettify.js              
./out/coverage/block-navigation.js                  
./out/coverage/prettify.js                          
./out/test.js                                       
./out/entry-_rollup-plugin-multi-entry:entry-point.js
./out/index.js                                      
./config/typedoc.js                                 
./config/rollup.js                                  
```

The `baseUrl` is the key to making those `src/Foo` imports work, I suspect, by making everything relative to the project root. While that has historically worked for the source, I have [had to do some rather hideous rewrites](https://github.com/ssube/noicejs/blob/master/config/webpack.js#L95).

Given the difference in output paths between api-extractor and rollup (and by extension tsc), it makes sense that api-extractor is not able to resolve the partial typedefs using the relative paths from `tsconfig.json`. There isn't a way to define those aliases in `tsconfig.json` or `api-extractor.json`, by chance? If not, I can look into replacing them with relative imports, but I have a few projects using this config and would like to be sure that the aliases are not viable before I start refactoring them all. :)

**Comment by octogonz** [comment]
> Output under the `src` folder? I'm not able to reproduce that, with a clean clone or in CI. Are you running `tsc` directly?

Regardless of how the toolchain invokes the compiler, running `tsc` from the command-line is a useful test of how other tools will interpret your project configuration.  Repro:

1. run `yarn install`
2. run `./node_modules/.bin/tsc`

> After running `make`, which runs `rollup` and then `tsc` via `rollup-plugin-typescript2`, the only output JS files I see are under `out/`:

I didn't try this because `make` didn't work on Windows.

> There isn't a way to define those aliases in `tsconfig.json` or `api-extractor.json`, by chance? If not, I can look into replacing them with relative imports, but I have a few projects using this config and would like to be sure that the aliases are not viable before I start replacing them all.

My impression is that this usage of `baseUrl` with absolute paths is unconventional.  I haven't seen other projects set up like that.  

Looking at your published NPM package's **noicejs.d.ts**, there's a bunch of `declare module` style paths like this:
```ts
. . .
declare module 'noicejs/error/ContainerBoundError' {
	import { BaseError } from 'noicejs/error/BaseError';
	export class ContainerBoundError extends BaseError {
	    constructor(msg?: string, ...nested: Array<Error>);
	}
}
declare module 'noicejs/error/ContainerNotBoundError' {
	import { BaseError } from 'noicejs/error/BaseError';
	export class ContainerNotBoundError extends BaseError {
	    constructor(msg?: string, ...nested: Array<Error>);
	}
}
declare module 'noicejs/error/InvalidProviderError' {
	import { BaseError } from 'noicejs/error/BaseError';
	export class InvalidProviderError extends BaseError {
	    constructor(msg?: string, ...nested: Array<Error>);
	}
}
. . .
```

This is a somewhat obsolete form that has mostly been replaced by ES6 `export` statements.  The newer form is more flexible, e.g. you can load two different versions of a library side-by-side, and it is more amenable to tree-shaking optimizations.  API Extractor doesn't support `declare module 'noicejs/error/InvalidProviderError' ` style imports, and I'm not sure it would be worth the effort to invest in that, given that it's fallen out of favor.

In my branch, the rollup you get uses `export` statements like this:

**noicejs.d.ts**
```
export declare class BaseError extends Error {
    message: string;
    stack?: string;
    protected nested: Array<Error>;
    constructor(message: string, ...nested: Array<Error>);
    cause(): Error | undefined;
    readonly length: number;
}

/**
 * Provider options.
 */
export declare interface BaseOptions {
    container: Container;
}

/**
 * Logger implementation using the console.
 */
export declare class ConsoleLogger implements Logger {
    static readonly global: ConsoleLogger;
    child(): Logger;
    debug(...params: Array<unknown>): void;
    info(...params: Array<unknown>): void;
    warn(...params: Array<unknown>): void;
    error(...params: Array<unknown>): void;
}
```

**Comment by octogonz** [comment]
@ssube  Should we close this issue then?
