### ISSUE TITLE
[rush] Add `--from-version-policy` flag

### ISSUE THREAD

**Issue by domarmstrong** [microsoft/web-build-tools#1494]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**What is the expected behavior?**

In the same way that we have --to and --from. It would be useful to have an opposite of --to-version-policy. We use the monorepo for applications and dependencies, --to-version-policy is very useful to be able to just build our dependencies without the apps. There are a few times when I've equally just wanted to build the apps, --from-version-policy=app would allow us to do this, and it feels like a pairing of commands already available with -f and -t.

**Comment by iclanton** [comment]
This seems useful. Want to take a crack at it?

**Comment by domarmstrong** [comment]
I could in a few weeks

**Comment by domarmstrong** [comment]
https://github.com/microsoft/web-build-tools/pull/1514

**Comment by iclanton** [comment]
This has been released in Rush 5.13.0.
