### ISSUE TITLE
[rush] `rush add` doesn't work with yarn

### ISSUE THREAD

**Issue by lhorie** [microsoft/web-build-tools#1527]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

Running `rush add` with yarn as the package manager doesn't work. After running it, it seems the lockfile gets into a bad state and we needed to run `rush update --full --purge` to get back to a working state

**Comment by bruk1977** [comment]
this looks a dupe

https://github.com/microsoft/web-build-tools/issues/1343

**Comment by rakeshpatnaik** [comment]
Closing this as a dupe. Tracking in #1343
