### ISSUE TITLE
[rush] - rush publish not publishing to private npm registry

### ISSUE THREAD

**Issue by sadsa** [microsoft/web-build-tools#1528]
**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

I don't know about anyone else, but I've spent the last 3 days trying to figure out how to publish my projects to our private npm repo. Any help would be much appreciated from those who have already gone through the same pain.

I have set the following settings in the rush.json:

```    
"projects": [
    {
      "packageName": "@ricado/arc-core",
      "projectFolder": "libraries/core",
      "reviewCategory": "libraries",
      "shouldPublish": true
    },
    {
      "packageName": "example-app",
      "projectFolder": "apps/example-app",
      "reviewCategory": "apps"
    }
]
```
My process is as follows:

1. `git checkout feature/123`
2. make changes, commit and push to remote branch
3. `git flow finish` (merges change into develop branch)
4. `rush change` to generate changelog files
5. `rush publish -a -p -b develop -r https://registry.npmjs.org/ -n ${NPM_TOKEN}`

It correctly adds git tags and pushes to our remote Bitbucket repo. However, there are no logs mentioning publishing to NPM.

Any help would be much appreciated.

* **Tool: Rush** 
* **Tool Version: Rush 5.13.0** 
* **Node Version: 10.16.1** 
* **OS: Windows 10**

**Comment by sadsa** [comment]
Well, now I'm really confused. I ran the following command this mornign and it worked.

`rush publish --apply --publish --target-branch develop --npm-auth-token ${NPM_TOKEN} --add-commit-details`

Maybe an error was thrown around formatting of the `--registry` or `-r` argument?

**Comment by rakeshpatnaik** [comment]
@iclanton

**Comment by iclanton** [comment]
That command should be correct. It sounds like things are working for you. Please reopen this issue if that's not the case.
