### ISSUE TITLE
[ts-command-line] missing argparse types

### ISSUE THREAD

**Issue by blacha** [microsoft/web-build-tools#1539]
## Please prefix the issue title with the project name i.e. [rush], [api-extractor] etc. ##

**Is this a feature or a bug?**

- [ ] Feature
- [x] Bug

**Please describe the actual behavior.**

The newly released `ts-command-line@4.3.0` breaks my build with 

```
node_modules/@microsoft/ts-command-line/dist/ts-command-line.d.ts:7:27 - error TS7016: Could not find a declaration file for module 'argparse'. '/home/runner/work/cogeotiff/cogeotiff/node_modules/argparse/index.js' implicitly has an 'any' type.
```

This is caused by `strict:true` or `noImplicitAny:true` in my tsconfig.json

It appears the `@type/argparse` was removed in https://github.com/microsoft/web-build-tools/commit/cc946ade38a55e6ff5dda75d694ec00613a26861#diff-752655588286d745397dc11cb871202d

I could work around this problem by including `@types/argparse` in my repo, however is this the desired behavior?

**If the issue is a bug, how can we reproduce it? Please provide detailed steps and include a GitHub branch if applicable. Your issue will get resolved faster if you can make it easy to investigate.**

Example broken build:  https://github.com/blacha/cogeotiff/pull/78/checks?check_run_id=233223740

Example simple repo that breaks on build: https://github.com/blacha/ts-command-broken
With failing build : https://github.com/blacha/ts-command-broken/commit/77528cebfa124789ca5057e7ee488beaa97f6254/checks

**What is the expected behavior?**
Ideally installing `yarn add -D @microsoft/ts-command-line` installs everything I need to work with it

**If this is a bug, please provide the tool version, Node.js version, and OS.**

* **Tool:** ts-command-line
* **Tool Version:**  4.3
* **Node Version:** 12.x
  * **Is this a LTS version?** No
  * **Have you tested on a LTS version?** No
* **OS:**  Linux

**Comment by iclanton** [comment]
Thanks for catching that! I've fixed the missing dependency in https://github.com/microsoft/web-build-tools/pull/1540

**Comment by iclanton** [comment]
Check out `ts-command-line` version 4.3.1
