### ISSUE TITLE
[rush] Feature request: monorepo level rush add

### ISSUE THREAD

**Issue by GongT** [microsoft/web-build-tools#1541]
**Is this a feature or a bug?**

- [x] Feature
- [ ] Bug

**description**
I have some custom command (like "node common/scripts/my-global-command.js") defined in `command-line.json`.    
And some hook script (like "postRushInstall: [common/scripts/post-install.js]") in `rush.json`.    

I need some extra modules *(eg: rimraf)* from these script. But no easy way to do this.

**workaround**
Add an extra private package in `projects`, it's "shouldPublish" defaults to false, set dependencies in it's package.json.    
After `rush install`, all package needed is in `common/temp/node_modules`    
In every script file, set module.paths to include this path.

**Comment by halfnibble** [comment]
I want to make sure that I understand your request. 

Let's say you have 100 projects in a monorepo. And your custom command needs dependencies A, B, and C, but none of your projects currently have those dependencies.

Would something like `rush add --all -p A -p B -p C` that updates the package.json of every project to include those dependencies work? I believe we have a PR in progress that adds this feature. https://github.com/microsoft/web-build-tools/pull/1434

**Comment by KevinTCoughlin** [comment]
FWIW, @halfnibble, my use case for a monorepo-wide `rush add` was as you described it above:

>Would something like rush add --all -p A -p B -p C that updates the package.json of every project to include those dependencies work? I believe we have a PR in progress that adds this feature. #1434

The above is also useful if updating a number of existing dependencies to a specific version. Currently it must be done with individual `rush add` calls or manual `package.json` manipulation. Here's my workaround PowerShell script: https://github.com/microsoft/ui-fabric-ts-validation/pull/4/files#diff-b2048f4d9ddfb134ca72c4d00f2feaa2R9

#1434 looks promising!

**Comment by GongT** [comment]
In fact, I do not know what is the best way to add dependency to my scripts.

`rush add --all` seems work, but is it really needed for add dependency for global script?

My script is used to maintaince my monorepo (eg. sync versions between package.json), it should not exists if I do not use a monorepo. so its dependency is not required by any of my projects.

Even `rush add --all` should resolve missing dependency, there's still a problem: how to require() them in my script?

**Comment by GongT** [comment]
Mark closed:

`add --all` resolve part of my problem.    
And I found a way to resolve require() problem. (but I need some test before post it out).
