### ISSUE TITLE
[rush] doubts in the publishing process

### ISSUE THREAD

**Issue by pantoninho** [microsoft/web-build-tools#1543]
- [x] misunderstanding
- [ ] Feature
- [ ] Bug

I'm trying out Rush and it has been great so far. I'm having some problems on the last step though -- publishing packages.
After setting my public packages (`shouldPublish=true`), I've created a PR targeting the master branch with all the changes gathered by `rush change`. What should be the next step now?

Should I merge the changes in master and use `rush publish` on that branch, or should I run `rush publish -b master` on the PR branch?

I've tried out both and I end up with the same problem -- after the publish commit has been done, rush updates dependants `package.json`s and tries to checkout to the desired branch:
```
* EXECUTING: git checkout master
error: Your local changes to the following files would be overwritten by checkout:
        packages/loader/package.json
Please commit your changes or stash them before you switch branches.
Aborting

ERROR: The command failed with exit code 1
```

Why is rush updating `package.json` after the 'publish' commit? Am I doing something wrong here? These are my steps:
       - open PR with `rush change` files commited
       - review PR, merge it
       - on master branch publish packages with `rush publish -a -b master -p`

Is there a better/correct way to do this? I would be happy to add a little bit more detail to the publishing guide if I'm able to understand the process throughly.

* **Tool: Rush ** 
* **Tool Version: Rush 5.13 ** 
* **Node Version: 10 ** 
* **OS: OSX **

**Comment by rakeshpatnaik** [comment]
Can you try out the steps outlined here and see if that resolves the issue? https://rushjs.io/pages/maintainer/publishing/ 
@sachinjoseph to provide more details

**Comment by pantoninho** [comment]
@rakeshpatnaik Thank you for your response. After further usage I was able to understand why it was happening (but it's weird nonetheless).
Apparently my `package.json` files were formatted in a different way than pnpm/rush wants and `rush publish` was checking out to the desired branch after the reformatting was done -- causing an error while checking out with modified files.

I solved my issue by commiting every `package.json` formatted by pnpm/rush and turning off any prettier effect over `package.json` files.

If you think that is not a problem, you may close this issue.

Thank you for this great tool

**Comment by iclanton** [comment]
There is another issue discussing not moving fields around in `package.json`s: https://github.com/microsoft/web-build-tools/issues/1503. I think your issue would be covered by that, so I'm going to close this issue in favor of that one.

**Comment by matthiasg** [comment]
Irrespective of the specific issue here it seems there is a lack of documentation on how to use branches for different change/[version]/publish scenarios. Where to use branches etc.
