### ISSUE TITLE
decouple from Gulp

### ISSUE THREAD

**Issue by ORESoftware** [Microsoft/web-build-tools#162]
I am looking into this tool to see if I can use it for my needs

I am working on this:
https://github.com/ORESoftware/npm-link-up

and I discovered Rush and Lerna in the process. One thing about Rush that threw me off - why is it so coupled with Gulp.js? I have seen some problems with Gulp over the years and it generally scares me.  Seems like using Bash would have been a better move, but maybe I missing something.

**Comment by qinweiz** [comment]
You can use other globally installed tools for build. Does that work for you?

Also, what problems with Gulp have you had?

**Comment by iclanton** [comment]
Rush shouldn't have any hard dependencies on Gulp. It uses the `scripts` section of the `package.json` file, from which you can call any tool you want.

I realize the Rush readme is a little misleading where it mentions that `rush rebuild` will call `gulp clean`, `gulp`, and `gulp test`, but if you take a look at the `scripts` section of the example `package.json` in [this section](https://github.com/Microsoft/web-build-tools/blob/master/rush/rush/README.md#configuring-a-project-to-be-built-by-rush), notice that the `clean`, `build`, and `test` scripts are configured. Rush *actually* calls `npm run clean` and `npm run test` during Rebuild.

I'll start updating the README accordingly.

**Comment by qz2017** [comment]
The problem is just that rush only detects local gulp, but does not detect other locally installed tools. That issue is tracked in issues#161.

**Comment by qz2017** [comment]
#161
