### ISSUE TITLE
Upgrade API extractor to TypeScript 2.3.1

### ISSUE THREAD

**Issue by christiango** [Microsoft/web-build-tools#165]
We're using API extractor and it has a peer dependency on 2.2.2, which seems to be blocking us from upgrading to 2.3.1.

**Comment by christiang88** [comment]
I'm looking at it now, feel free to assign it to me

**Comment by qz2017** [comment]
We are skipping Typescript 2.3.1 and waiting for 2.3.3,  because 2.3.1 and 2.3.2 have some issues, e.g. [TypeScript 15546 ](https://github.com/Microsoft/TypeScript/issues/15546).
