### ISSUE TITLE
gulp-core-build-sass emits legacy export assignment

### ISSUE THREAD

**Issue by fuocor** [Microsoft/web-build-tools#229]
the gulp-core-build-sass is using "export = styles" rather than "export default styles" when no module name is specified

**Comment by iclanton** [comment]
If the [module name](https://github.com/Microsoft/web-build-tools/blob/master/core-build/gulp-core-build-sass/src/SassTask.ts#L43-L48) is set to the empty string (`''`), the `export = styles` style export is used. If it's set to `null` or `undefined`, the `export default styles;` style export is used. Try setting that configuration value to `null` or `undefined`.
