### ISSUE TITLE
Project dependencies

### ISSUE THREAD

**Issue by fuocor** [Microsoft/web-build-tools#230]
It's not at all clear how to get project dependencies to work.

If I create ProjextA and ProjectB (dependency of A) at the same time how do I get B linked to A?
Adding B to the project.json of A result in "rush generate" failing and "cyclicDependencyProjects" in rush.json does not seem to have any effect.

thanks,
rich

**Comment by qz2017** [comment]
You can use a lower/published version of B in project.json of A. Then A is built with a slightly older version of B.  One project has to be built first with all available dependencies.

**Comment by nickpape-msft** [comment]
Hi @fuocor,

To be clear, you are attempting to simply link 2 projects together? You should simply be able to add both projects to your `rush.json`, add a dependency to ProjectB in the `package.json` of ProjectA, then run "rush install". As long as the version specifier used in the package.json of ProjectA is compatible with the version specified in ProjectB's `package.json` everything should link correctly.

For example:

ProjectA's package.json
```
{
  "name": "project-a",
  "version": "1.1.1"
}
```

ProjectB's package.json
```
{
  "name": "project-b",
  "version": "1.0.0",
  "dependencies": {
    "project-a": ">=1.0.0 <2.0.0"
  }
}
```

Note that in Rush3, you only need to run "rush generate" if "rush install" tells you it is necessary.

**Comment by fuocor** [comment]
I thought I did that ( a few times ...)  to have the rush generate fail
I tried again ...and...  I guess doing on a Friday morning at 5:30 fixed the problem ;). 
Yesterday must have been a really bad karma day for me 

thanks.
