### ISSUE TITLE
Outdated link

### ISSUE THREAD

**Issue by theJian** [Microsoft/web-build-tools#246]
The link pointed to `rush-schema.json` in [wiki](https://github.com/Microsoft/web-build-tools/wiki/Rush-~-Setting-up-your-repo#step-1-create-rushjson) is outdated. The file now is named `rush.schema.json` and located in `https://github.com/Microsoft/web-build-tools/blob/master/apps/rush-lib/src/rush.schema.json`.

**Comment by qz2017** [comment]
Thanks for pointing it out. The wiki page has been updated.
