### ISSUE TITLE
build.addSuppression support regex?

### ISSUE THREAD

**Issue by ipip2005** [Microsoft/web-build-tools#264]
There were some warnings that will print local path (C:/Users/xxx/GitRepos/...) that variant in different machines.
If the `addSuppression` method can support regex, then we can filter these kinds of warning logs out and bypass the build.

**Comment by nickpape-msft** [comment]
Hi @ipip2005, that is a good suggestion.

We are eventually planning on overhauling and improving the entire error handling experience to make it more structured and easy to use.

In the short-run, I've opened a PR #268 which adds a Regex-based suppression function.

**Comment by nickpape-msft** [comment]
This has been fixed by #268
