### ISSUE TITLE
Missing package from wiki: ts-spec-gen

### ISSUE THREAD

**Issue by MartynasZilinskas** [Microsoft/web-build-tools#265]
I found in `api-extractor` wiki link to a package, which repository is not found.
```
For each project, API Extractor also outputs a JSON file that is used to generate online documentation. Our online documentation looks like this. It is produced by a pipeline:

api-extractor --> sp-core-library.api.json --> ts-spec-gen --> sp-core-library.md --> custom markdown template --> HTML output
```
[Link to wiki](https://github.com/Microsoft/web-build-tools/wiki/API-Extractor-~-Feature-walkthrough)

Is this package still available somewhere? I think it would actually help a lot for documentation generation from json file.

**Comment by pgonzal** [comment]
Closing this issue, since we decided to create more reusable tooling in the discussion for #292
