### ISSUE TITLE
[rush] "rush change" needs to detect where the rush.json file is relative to the git repo

### ISSUE THREAD

**Issue by nickpape** [microsoft/web-build-tools#270]
Right now this causes issues if your rush.json is not in the root of your repository.

Essentially, `rush change` is using relative paths from git to determine which project a changed file belongs to, however, the rush.json has paths that are relative to its location, whereas git has paths that are relative to the root of the repo.

The fix for this should be relatively straightforward. Whenever we do Git-based operations, we should append the relative path to the rush.json file to the relativeFolderPath's for each project.

Most likely this also affects incremental build.

**Comment by halfnibble** [comment]
@Lincoded lower priority than your current task. I'm just trying to divvy up the issue goods.

**Comment by halfnibble** [comment]
Assigning to @claudiazhaoya.

**Comment by iclanton** [comment]
The fix for this has been released in Rush 5.12.0
