### ISSUE TITLE
IChangelog should have Date class instead of string for `date` property

### ISSUE THREAD

**Issue by nickpape-msft** [Microsoft/web-build-tools#280]
We should use Date.

Currently the change log processor has a bug where different date strings in the JSON file are passed through verbatim to the Markdown file.

The Markdown renderer should determine the date format, not the JSON file.

**Comment by qz2017** [comment]
That should be fine. The data entry is whatever in changelog.json file as UTC. Markdown renderer has the freedom to construct it again and change the format.
