### ISSUE TITLE
[api-extractor] Missing specific kind property string in IDocElement.

### ISSUE THREAD

**Issue by MartynasZilinskas** [Microsoft/web-build-tools#295]
Specific "kind" property is missing in interfaces.
[IHrefLinkElement](https://github.com/Microsoft/web-build-tools/blob/master/libraries/api-extractor/src/IDocElement.ts#L32-L47) and [ICodeLinkElement ](https://github.com/Microsoft/web-build-tools/blob/master/libraries/api-extractor/src/IDocElement.ts#L53-L84) should have `kind: 'linkDocElement';`.
Because this string is used: [here](https://github.com/Microsoft/web-build-tools/blob/5513858b1d478bd5670e9a738936b0e87a88aab3/libraries/api-extractor/src/DocElementParser.ts#L171-L176) and [here](https://github.com/Microsoft/web-build-tools/blob/5513858b1d478bd5670e9a738936b0e87a88aab3/libraries/api-extractor/src/DocElementParser.ts#L190-L198).

That will provide type checking in links mentioned above, moreover type gates would work:
```ts
switch (item.kind) {
    case "textDocElement": {
        return textElement.value;
    }
    case "linkDocElement": {
        switch (item.referenceType) {
            case "href": {
                // Do something about href
            }
            case "code": {
                // Do something about code
            }
        }
    }
}
```

**Comment by pgonzal** [comment]
The plan is to replace this with the new [MarkupElement](https://github.com/Microsoft/web-build-tools/blob/master/libraries/api-extractor/src/markup/MarkupElement.ts) data structure, which will unify the way rich text is represented across the documentation pipeline.  This will be completed by the end of this month.

**Comment by nickpape-msft** [comment]
@pgonzal can this issue be closed?

**Comment by pgonzal** [comment]
This issue was already fixed.   ICodeLinkElement was replaced by [IMarkupApiLink](https://github.com/Microsoft/web-build-tools/blob/master/apps/api-extractor/src/markup/MarkupElement.ts] which does not have that problem.
