### ISSUE TITLE
typescript task inlines content into sourcemaps

### ISSUE THREAD

**Issue by fuocor** [Microsoft/web-build-tools#305]
The typescript task inlines the file contents into the source maps with no way to override it.

By default gulp-sourcemaps includes the content when generating the files. Unfortunately, this is a problem when debugging node projects or chrome workspace mapped files because breakpoints are not recognized on the local files.

There needs to be a way to provide includeContent: false to gulp-sourcemaps 

thanks,
rich

**Comment by fuocor** [comment]
in the _compileProject function of the task if

`jsResult = jsResult.pipe(sourcemaps.write('.', { sourceRoot: this._resolveSourceMapRoot }));`

is changed to:

`jsResult = jsResult.pipe(sourcemaps.write('.', { sourceRoot: "../../<gulpfile_dir>/src", includeContent: false }));`

then it maps the correct place.

rich

**Comment by fuocor** [comment]
BTW - the following changes to the package gulpfile  generates the correct source maps

build.TypeScriptConfiguration.setTypescriptCompiler(require('typescript'));
build.typescript['_tsES6Project'] = ts.createProject('tsconfig.json', { module: 'commonjs' });
build.typescript.taskConfig.libDir = './trash'
build.typescript.taskConfig.libES6Dir = './lib'

**Comment by nickpape-msft** [comment]
@iclanton Can you take a look. This looks similar to #310

**Comment by pgonzal** [comment]
This issue is no longer relevant after PR https://github.com/Microsoft/web-build-tools/pull/791 which invoke the compiler with a more modern configuration that should not have this issue.
