### ISSUE TITLE
gulp-sourcemap differences

### ISSUE THREAD

**Issue by fuocor** [Microsoft/web-build-tools#310]
I have a config that includes the following:

`build.typescript.taskConfig.libES6Dir = './es6';`
`build.typescript.taskConfig.libDir = './lib';`

the problem is that the source maps point to 2 different locations.

lib pointing to: 
`{"version":3,"sources":["../../src/index.ts"],"names":[],"mappings":";;;AAAA,yDAA+B;AAC/B,uDAA6B;AAC7B,yDAA+B","file":"index.js","sourcesContent":["export * from \"./common/index\";\r\nexport * from \"./site/index\";\r\nexport * from \"./tenant/index\";\r\n"],"sourceRoot":"..\\src"}`

and es6 pointing to: 
`{"version":3,"sources":["../src/index.ts"],"names":[],"mappings":"AAAA,cAAc,gBAAgB,CAAC;AAC/B,cAAc,cAAc,CAAC;AAC7B,cAAc,gBAAgB,CAAC","file":"index.js","sourcesContent":["export * from \"./common/index\";\r\nexport * from \"./site/index\";\r\nexport * from \"./tenant/index\";\r\n"],"sourceRoot":"..\\src"}`

this is a real show stopper in trying to get node projects debugged with commonjs.

If I run the default tsc. I get 
`{"version":3,"file":"index.js","sourceRoot":"","sources":["../src/index.ts"],"names":[],"mappings":";;;AAAA,yDAA+B;AAC/B,uDAA6B;AAC7B,yDAA+B"}`

rich

**Comment by fuocor** [comment]
BTW - the following changes to the package gulpfile  generates the correct source maps

build.TypeScriptConfiguration.setTypescriptCompiler(require('typescript'));
build.typescript['_tsES6Project'] = ts.createProject('tsconfig.json', { module: 'commonjs' });
build.typescript.taskConfig.libDir = './trash'
build.typescript.taskConfig.libES6Dir = './lib'

**Comment by iclanton** [comment]
Seems like the TypeScript compilation configuration is missing a sourcemap property. If you add a `"inlineSources": true` property to your `tsconfig.json`, that may fix it.

**Comment by nickpape-msft** [comment]
@fuocor is this issue fixed?

**Comment by pgonzal** [comment]
This issue is no longer relevant after PR https://github.com/Microsoft/web-build-tools/pull/791 which invoke the compiler with a more modern configuration that should not have this issue.
