### ISSUE TITLE
@microsoft/load-themed-styles 1.7.0 breaks package layout, AMD version missing

### ISSUE THREAD

**Issue by abettadapur** [Microsoft/web-build-tools#314]
The latest version of this package did not follow semver practices and changed the package layout compared to 1.6.0. The lib-amd folder was removed from this package.

Is lib-amd no longer going to be packaged with this library?

1.6.0
![image](https://user-images.githubusercontent.com/2415669/29329788-dd54817c-81ab-11e7-8502-d178f5b85de2.png)

1.7.0
![image](https://user-images.githubusercontent.com/2415669/29329814-f1efdd34-81ab-11e7-9ded-56d5b39776ca.png)

**Comment by qz2017** [comment]
@iclanton has fixed it. Please wait for the next release.

**Comment by iclanton** [comment]
This has been fixed in 1.7.1. The `lib-amd` directory was accidentally removed by an update to the `.npmignore` file.

It should be released in a few minutes.
