### ISSUE TITLE
[web-library-build] Sourcemaps do not map to typescript sources

### ISSUE THREAD

**Issue by kollster** [Microsoft/web-build-tools#319]
This issue is regarding to the ```web-library-build``` package version 3.2.8.

When using web-library-build with no customization, the bundle task creates sourcemaps that map to compiled js-files in lib folder instead of their original typescript sources.

The default project layout is:
dist/
lib/
src/

As far as I can understand, the bundle task uses the build task to compile typescript files and corresponding sourcemaps to the lib-folder. Then the webpack task bundles these compiled js-files to a bundle in the dist-folder together with a sourcemap file. However this sourcemap file does not map to the original typescript sources - it only maps to the js-files in lib-folder.

Is there a way to enable the correct mapping?

**Comment by fuocor** [comment]
Same problem as: [here](https://github.com/Microsoft/web-build-tools/issues/310)

**Comment by fuocor** [comment]
BTW - the following changes to the package gulpfile  generates the correct source maps

build.TypeScriptConfiguration.setTypescriptCompiler(require('typescript'));
build.typescript['_tsES6Project'] = ts.createProject('tsconfig.json', { module: 'commonjs' });
build.typescript.taskConfig.libDir = './trash'
build.typescript.taskConfig.libES6Dir = './lib'

**Comment by iclanton** [comment]
WRT your `build.TypeScriptConfiguration.setTypescriptCompiler(require('typescript'));` line - which version of TypeScript do you have in your `package.json`?

Interesting that changing the compilation mode to es6 fixes a sourcemap issue. I'm guessing the root of the issue is that the OOB webpack configuration is missing the source-map-loader.

Can you try installing the `source-map-loader` package and adding this block to your webpack configuration:

```TypeScript
module: {
  rules: [
    {
      test: /\.js$/,
      enforce: 'pre',
      use: require.resolve('source-map-loader')
    }
  ]
}
```

Or if you have a repro in a GitHub repo you can share, I can try it out myself.

**Comment by kollster** [comment]
@iclanton Sorry for the late response.
Now, I have tried installing ```"source-map-loader": "0.2.1"``` and I have added the suggested rule wo my webpack.config.js:
```javascript
module: {
  rules: [
    {
      test: /\.js$/,
      enforce: 'pre',
      use: require.resolve('source-map-loader')
    }
  ]
}
```
**And now it works!** I can place breakpoints in the typescript sources, and everything work just as expected 👍 Thank you for the input!

By the way, I am using the following versions of relevant software:
```
    "@microsoft/web-library-build": "4.0.7",
    "gulp": "3.9.1",
    "typescript": "2.5.2",
    "source-map-loader": "0.2.1",
    "webpack": "3.5.6"
```
Is this sourcemap setup something that should be incorporated in ```@microsoft/web-library-build```?

**Comment by nickpape-msft** [comment]
@iclanton , do we need to add sourcemap setup directly into web-library-build or gulp-core-build-webpack?
