### ISSUE TITLE
Rush change: use the correct remote in github scenarios

### ISSUE THREAD

**Issue by dzearing** [Microsoft/web-build-tools#320]
I see empty change files in fabric-react nearly every day. Example:

https://github.com/OfficeDev/office-ui-fabric-react/pull/2514/files

This was because it’s comparing against “origin/master”, which is the wrong remote.

It’s not the end of the world, but it would really be nice to fix `rush change` to compare against the correct remote. This can be deduced a number of ways. For example, package.json has the repository details in there.

I have a really hard time explaining the “-b” parameter to people because I have no idea what the dev called their officedev remote, if they even made one. This is a really annoying issue that makes rush awkward to use in github scenarios where people normally fork the repo and work from the fork. Thankfully we can ignore the extra files, but I’m a little worried by comparing against the wrong remote we may miss a change.

**Comment by qz2017** [comment]
https://github.com/Microsoft/web-build-tools/pull/328

**Comment by qz2017** [comment]
It is supported in rush 3.0.15
