### ISSUE TITLE
Rush: Can't get change/publish to work?

### ISSUE THREAD

**Issue by timneedham** [Microsoft/web-build-tools#327]
Hi,

`rush version 3.0.11`

Help! `rush change` always results in `No change file is needed` and `rush publish` doesn't seem do anything... even though we've changed loads of projects inside our monorepo.

**Am I missing something (can't find anything in the docs)?**

* Our work-in-progress monorepo lives __[here](https://github.com/wmfs/tymly)__ if that helps.

One of the reasons for using Rush was to help take the sting out out of publishing, any help gratefully received!

Thanks

**Comment by qz2017** [comment]
To make rush change or rush publish do things, you need to mark the projects you want to publish with a flag "shouldPublish" first, like here: https://github.com/Microsoft/web-build-tools/blob/a19b03c0c50ac90b4038ff951301e901ce96e3d3/rush.json#L61

**Comment by timneedham** [comment]
Thanks @qz2017 

Doesn't seem `shouldPublish` isn't mentioned anywhere in the docs  - just the change log?

**Comment by nickpape-msft** [comment]
Thanks @timneedham , I have updated our documentation to mention the `shouldPublish` flag.
