### ISSUE TITLE
Can't install the package by command "npm install @microsoft/node-core-library"

### ISSUE THREAD

**Issue by farawayplace613** [Microsoft/web-build-tools#335]
Error message is,
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\abrcheng\\AppData\\Roaming\\npm\\node_modules\\npm
\\bin\\npm-cli.js" "install" "@microsoft/node-core-library"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 Not found : @microsoft/node-core-library
npm ERR! 404
npm ERR! 404  '@microsoft/node-core-library' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\spfx\githubdemos\GDPR\sp-dev-gdpr-activity-hub\GDPRStarterKit\npm-debug.log[](url)

Debug information in npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\abrcheng\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '@microsoft/node-core-library' ]
2 info using npm@3.10.10
3 info using node@v6.11.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @microsoft/node-core-library
8 silly fetchNamedPackageData @microsoft/node-core-library
9 silly mapToRegistry name @microsoft/node-core-library
10 silly mapToRegistry scope (from package name) @microsoft
11 verbose mapToRegistry no registry URL found in name for scope @microsoft
12 silly mapToRegistry using default registry
13 silly mapToRegistry registry https://registry.npmjs.org/
14 silly mapToRegistry data Result {
14 silly mapToRegistry   raw: '@microsoft/node-core-library',
14 silly mapToRegistry   scope: '@microsoft',
14 silly mapToRegistry   escapedName: '@microsoft%2fnode-core-library',
14 silly mapToRegistry   name: '@microsoft/node-core-library',
14 silly mapToRegistry   rawSpec: '',
14 silly mapToRegistry   spec: 'latest',
14 silly mapToRegistry   type: 'tag' }
15 silly mapToRegistry uri https://registry.npmjs.org/@microsoft%2fnode-core-library
16 verbose request uri https://registry.npmjs.org/@microsoft%2fnode-core-library
17 verbose request no auth needed
18 info attempt registry request try #1 at 17:22:02
19 verbose request id 4890c9ce289e249f
20 http request GET https://registry.npmjs.org/@microsoft%2fnode-core-library
21 http 404 https://registry.npmjs.org/@microsoft%2fnode-core-library
22 verbose headers { 'content-type': 'application/json',
22 verbose headers   'cache-control': 'max-age=0',
22 verbose headers   'content-length': '21',
22 verbose headers   'accept-ranges': 'bytes',
22 verbose headers   date: 'Wed, 30 Aug 2017 09:22:03 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-nrt6132-NRT',
22 verbose headers   'x-cache': 'MISS',
22 verbose headers   'x-cache-hits': '0',
22 verbose headers   'x-timer': 'S1504084924.598008,VS0,VE132' }
23 silly get cb [ 404,
23 silly get   { 'content-type': 'application/json',
23 silly get     'cache-control': 'max-age=0',
23 silly get     'content-length': '21',
23 silly get     'accept-ranges': 'bytes',
23 silly get     date: 'Wed, 30 Aug 2017 09:22:03 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-nrt6132-NRT',
23 silly get     'x-cache': 'MISS',
23 silly get     'x-cache-hits': '0',
23 silly get     'x-timer': 'S1504084924.598008,VS0,VE132' } ]
24 silly fetchPackageMetaData Error: Not found : @microsoft/node-core-library
24 silly fetchPackageMetaData     at makeError (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
24 silly fetchPackageMetaData     at Request._callback (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:187:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1048:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:969:12)
24 silly fetchPackageMetaData  error for @microsoft/node-core-library { Error: Not found : @microsoft/node-core-library
24 silly fetchPackageMetaData     at makeError (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
24 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
24 silly fetchPackageMetaData     at Request._callback (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
24 silly fetchPackageMetaData     at Request.self.callback (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:187:22)
24 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
24 silly fetchPackageMetaData     at Request.<anonymous> (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1048:10)
24 silly fetchPackageMetaData     at emitOne (events.js:96:13)
24 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
24 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:969:12)
24 silly fetchPackageMetaData   pkgid: '@microsoft/node-core-library',
24 silly fetchPackageMetaData   statusCode: 404,
24 silly fetchPackageMetaData   code: 'E404' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
27 silly runTopLevelLifecycles Finishing
28 silly install printInstalled
29 verbose stack Error: Not found : @microsoft/node-core-library
29 verbose stack     at makeError (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
29 verbose stack     at CachingRegistryClient.<anonymous> (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:290:14)
29 verbose stack     at Request._callback (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
29 verbose stack     at Request.self.callback (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:187:22)
29 verbose stack     at emitTwo (events.js:106:13)
29 verbose stack     at Request.emit (events.js:191:7)
29 verbose stack     at Request.<anonymous> (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:1048:10)
29 verbose stack     at emitOne (events.js:96:13)
29 verbose stack     at Request.emit (events.js:188:7)
29 verbose stack     at IncomingMessage.<anonymous> (C:\Users\abrcheng\AppData\Roaming\npm\node_modules\npm\node_modules\request\request.js:969:12)
30 verbose statusCode 404
31 verbose pkgid @microsoft/node-core-library
32 verbose cwd E:\spfx\githubdemos\GDPR\sp-dev-gdpr-activity-hub\GDPRStarterKit
33 error Windows_NT 6.3.9600
34 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\abrcheng\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@microsoft/node-core-library"
35 error node v6.11.1
36 error npm  v3.10.10
37 error code E404
38 error 404 Not found : @microsoft/node-core-library
39 error 404
40 error 404 '@microsoft/node-core-library' is not in the npm registry.
41 error 404 You should bug the author to publish it (or use the name yourself!)
42 error 404 Note that you can also install from a
43 error 404 tarball, folder, http url, or git url.
44 verbose exit [ 1, true ]

**Comment by MaximDelyukin** [comment]
Hi all,
Same issue here.

**Comment by eHyve** [comment]
Hi All,
I am currently having the same issue. It was working OK yesterday for me.
Thanks for any help

**Comment by BoehnMa** [comment]
Hi all,
also for me today the same issue. Yesterday no issues. 
Please help!
Thanks - Matthias

**Comment by paololec** [comment]
Me too.

**Comment by qz2017** [comment]
It should have been solved. Please try again. Feel free to reopen the issue if it still happens to you. Sorry for the inconvenience.
