### ISSUE TITLE
Error when start "gulp serve"

### ISSUE THREAD

**Issue by BoehnMa** [Microsoft/web-build-tools#344]
## What I did:
1. "npm install" on a spfx sample project (https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/js-display-list) 
2. Try to make it run with "gulp serve".

## The error I get:
E:\dev\admboehnma\ttt\js-display-list>gulp serve
Build target: DEBUG
TypeError: Cannot read property 'readCommentedJsonFile' of undefined
TypeError: Cannot read property 'readCommentedJsonFile' of undefined
[12:59:01] Error - Unknown
 undefined
[12:59:02] ==================[ Finished ]==================
[12:59:02] Project js-display-list version: 0.0.2
[12:59:02] Build tools version: 2.10.0
[12:59:02] Node version: v6.11.2
[12:59:02] Total duration: 4.08 s
[12:59:02] Task errors: 2

The problem is new. The day before yesterday this worked without any issues.

Thanks for help!

**Comment by nickpape-msft** [comment]
Hi @BoehnMa, we had a regression occur for some older packages (as they had too loose of SemVer patterns and picked up a breaking change). This issue was addressed early last week. Could you try deleting and reinstalling your node_modules folder to pick up the fixed packages?

**Comment by pgonzal** [comment]
Yes, it should have been fixed by #347 **Republish last major release of core build libraries to fix compatibility issue**.
