### ISSUE TITLE
rush link ERROR: Failed to parse package.json for <project>: Invalid version: "file:projects/<project>.tgz"

### ISSUE THREAD

**Issue by fuocor** [Microsoft/web-build-tools#354]
Rush Multi-Package Build Tool 3.0.15

running rush install then rush link results in the error:

ERROR: Failed to parse package.json for <project>: Invalid version: "file:projects/<project>.tgz"

whereas running rush generate links everything fine

not sure where to start looking additional diagnostics

regards

**Comment by nickpape-msft** [comment]
Hi @fuocor,

There was [a change](https://github.com/Microsoft/web-build-tools/wiki#september-5-2017---changes-requiring-action-in-rush-3015) made in the 3.0.15 release that requires you to run **rush generate**. To resolve the issue, please run **rush generate** and checkin the resulting changes to your shrinkwrap file.

**Comment by fuocor** [comment]
thanks...

**Comment by HipsterZipster** [comment]
This is a really annoying issue when `rush generate` takes a long time to run. Just adding or updating a single npm module shouldn't require regenerating everything
