### ISSUE TITLE
[gulp-core-build] Set/replace SASS variables in gulp

### ISSUE THREAD

**Issue by NickSevens** [microsoft/web-build-tools#365]
Is it possible in any way to change SASS variables at compile time?

Specifically, I need to change relative IMG base paths.
E.g: I have images in a SharePoint /Style Library. However, since `gulp-core-build-sass` injects the output CSS as JS, the relative paths do not work anymore. This could be resolved/worked around if I could specify an absolute path when running gulp.

Thanks.

**Comment by halfnibble** [comment]
I am going to mark this as "won't fix" because it will be much easier to perform this action with a custom webpack loader, and we are migrating core-build tasks to webpack.
