### ISSUE TITLE
[load-themed-styles] Styles not loading in IE11

### ISSUE THREAD

**Issue by NickSevens** [microsoft/web-build-tools#388]
I'm using `@microsoft/gulp-core-build-sass` in combination with `@microsoft/loader-load-themed-styles` to load my themed CSS in a webpack bundle.
This works fine 90% of the time, but:
- in **chrome** sometimes (+/- 5% of the time) the CSS is not loaded. when selecting a DOM node in dev tools, no classes are attached to the element, and indeed, in the HTML the custom css's <style> tag is nowhere to be found.
- in **IE11**, with **document mode set to IE11** the CSS is **never** loaded. Same issue here in dev tools.
- in **IE11**, with **document mode set to IE10**, I have not seen any issues. Granted - the amount of tries have been limited.

So, it seems that the `loadStyles` function is called too soon, which results in the css not being loaded on the page.

If anyone could point me in the right direction as to why this occurs, it'd be very helpful!

PS: the outputted webpack bundles are used on a SharePoint Online publishing page.

**Comment by pgonzal** [comment]
@iclanton @srideshpande could you guys take a look at this before we release the new **load-themed-styles**?

**Comment by NickSevens** [comment]
I've been debugging this issue for quite a while, and depending on browser and document mode, I see different values in the `__themeState__` object, especially in the `registeredStyles` and `registeredThemableStyles` arrays.
In our case, this resulted in:
- in **Chrome**, the theme was loaded and variables were injected correctly (most of the time, see first post)
- in **IE11**, with **document mode set to IE11**, no custom CSS was loaded
- in **IE11**, with **document mode set to IE10**, css was loaded, but the **default value** was injected and never replaces by the theme value. (eg: [theme: myCustomColor, default: red] resulted in **red** used no matter what theme was set).

I ended up removing `load-themed-styles` from our solution, loading a fixed css file instead. **But**, we do still see occasional css issues in `office-ui-fabric-react` components - where no css seems to be loaded at all, looking like the same issue we had in our own components.

**Comment by iclanton** [comment]
Can you provide a repro environment?

@dzearing - have you seen this before?

**Comment by dzearing** [comment]
Hmm. No we haven't. It would be good to have a repro.
Mentioning @jijizz as he may have seen it as well.

**Comment by NickSevens** [comment]
I'll try to fix a small repro as soon as I find some time. Will let you guys know.

**Comment by NickSevens** [comment]
@dzearing @iclanton I've created a small repo at https://github.com/NickSevens/web-build-tools-issue-388 which shows the difference in IE10 vs Chrome.
I can't find an easy way to show the "not loading css" however...

I did also notice it happens more often when internet connection is slow(er).

I do realize this could be a very specific issue, with lots of race conditions, especially on top of a SharePoint environment...

**Comment by iclanton** [comment]
I'm having trouble seeing a repro of the IE11 issue, even when simulating modem speeds using Fiddler. I do see styles not getting added to the page in IE10, so we're investigating that issue.

Can you get a consistent repro of the issue you're seeing in IE11?

**Comment by NickSevens** [comment]
Unfortunately I can't get a repro of the "no css at all" issue :/
The IE10 part would be nice already though :)

**Comment by olemp** [comment]
I have this issue aswell, in Chrome. Sometimes 1 in 20 page loads, sometimes 1 in 10. It's very random.

**Comment by nickpape-msft** [comment]
@iclanton @olemp @NickSevens  Is this issue still occurring?

**Comment by NickSevens** [comment]
@nickpape-msft we're still working with the workaround: exporting all styles in a separate css, so I can't really say. However, we did see the same type of issue occuring with ui fabric controls, and that has been a while since I've seen it...

**Comment by olemp** [comment]
@nickpape-msft Yep, still occurs now and then. 2/10 page loads or so.
