### ISSUE TITLE
Expose repo for sp-build-core-tasks

### ISSUE THREAD

**Issue by bpkennedy** [Microsoft/web-build-tools#438]
You have empty reference documentation on the [@microsoft/gulp-core-build](https://github.com/Microsoft/web-build-tools/blob/master/core-build/gulp-core-build/README.md) page to [sp-build-core-tasks](https://www.npmjs.com/package/@microsoft/sp-build-core-tasks).

I would like to look at the code (preferably read some documentation on how these are put together and work) for sp-build-core-tasks.  However that link is to a reference on npm (no github repo).  I must install this via npm and look through the files that way.

**Comment by pgonzal** [comment]
We've removed the reference.  The **web-build-tools** repo is for general build tools which with an open source license.

The **sp-build-core-tasks** project is part of the SharePoint Framework, which has a commercial license.  The best place to request features would be [SharePoint Framework UserVoice](https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/filters/top?category_id=194590).  This will allow other developers to vote for your suggestion.  Microsoft prioritizes requests based on popularity.

That said, if you simply want to "look at the code" (versus fork or contribute), the NPM packages that we publish include *.js and *.d.ts files which contain most of what you need to understand how the system works.  They are runnable in the VS Code debugger.
