### ISSUE TITLE
SharePoint Framework: gulp serve stops working on typescript compile error

### ISSUE THREAD

**Issue by kurky91** [Microsoft/web-build-tools#463]
1. Created new SharePoint Framework with yo @microsoft/generator-sharepoint
2. Chose react framework

When running gulp serve and writing a typescript error the watchers stop working.
gulp serve needs to be restarted to get the watchers working again.

In file .\node_modules\@microsoft\gulp-core-build-typescript\lib\TypeScriptTask.js:

When I comment out result.errorCount++ in the plumber errorHandler method the watchers work as expected -> they recompile if I fix the typescript error.

**Comment by pgonzal** [comment]
This git repo is for the open source tooling.  Please file your issue on the [SharePoint Framework GitHub](https://github.com/SharePoint/sp-dev-docs/issues).

If you are able to repro your issue using **gulp-core-build** directly (without **sp-build-web**), please reopen this issue and provide the repro steps.  Thanks!
