### ISSUE TITLE
Webpack failed on version 1.7.26

### ISSUE THREAD

**Issue by nguyentoantuit** [Microsoft/web-build-tools#511]
Hi all,
After new release was published, the weckpack had failed. I had checked there is not thing excepted CHANGELOG, package.json and README  after I ran npm install --save @microsoft/load-themed-styles@1.7.26
![image](https://user-images.githubusercontent.com/6096518/35430654-d1db552e-02ab-11e8-95b6-f9532cda6016.png)

**Comment by bradleyzhou** [comment]
Me too here on `load-themed-styles`. For more info, to reproduce,
```bash
mkdir tmp && cd tmp
npm init
```

For version `1.7.26`
```bash
npm install --no-save @microsoft/load-themed-styles@1.7.26
tree node_modules/\@microsoft/load-themed-styles/
## will output
├── CHANGELOG.json
├── CHANGELOG.md
├── LICENSE
├── README.md
└── package.json
```

For version `1.7.25`
```bash
npm install --no-save @microsoft/load-themed-styles@1.7.25
tree node_modules/\@microsoft/load-themed-styles/
## will output
├── CHANGELOG.json
├── CHANGELOG.md
├── LICENSE
├── README.md
├── lib
│   ├── index.d.ts
│   ├── index.js
│   ├── index.js.map
│   └── test
│       ├── index.test.d.ts
│       ├── index.test.js
│       └── index.test.js.map
├── lib-amd
│   ├── index.d.ts
│   ├── index.js
│   ├── index.js.map
│   └── test
│       ├── index.test.d.ts
│       ├── index.test.js
│       └── index.test.js.map
└── package.json
```

**Comment by nickpape-msft** [comment]
Looks like there was a hiccup in the release process yesterday. I went ahead and unpublished 1.7.26, so you should be getting 1.7.25 when you `npm install @microsoft/load-themed-styles@latest`.

**Comment by nickpape-msft** [comment]
We unpublished all the empty packages and then re-published everything in the web-build-tools repo, so this issue should be mitigated. Feel free to open a new issue if you see any new problems.

**Comment by wattlebird** [comment]
@nickpape-msft Dear nickpape, it seems same problem occurs for v1.7.80 also. Would you please check it?

**Comment by nguyentoantuit** [comment]
@wattlebird cc @nickpape-msft 
Yep, I ran into this issue again and report a issue at https://github.com/OfficeDev/office-ui-fabric-react/issues/6042

**Comment by wattlebird** [comment]
@nguyentoantuit Well, seems v1.7.81 is valid now.

**Comment by pgonzal** [comment]
The full story is here: https://github.com/Microsoft/web-build-tools/issues/782
