### ISSUE TITLE
[rush] Allow greater-than versions of Node

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [microsoft/web-build-tools#516]
Forking from https://github.com/OfficeDev/office-ui-fabric-react/pull/3826#issuecomment-361710024:

> That said, if you've decided to work in an unsupported state, it seems a little inelegant to have to keep editing rush.json every time you pull from master. Maybe there should be a setting that allows you to permanently override the policy (and see a disclaimer reminding you that you're in an unsupported state).

I agree that it would be nice to not have it error anything: perhaps a warning?

**Comment by pgonzal** [comment]
I'd suggest to model this [as an environment variable](https://github.com/Microsoft/web-build-tools/blob/226dbef4ac525a7fb1a1df51b3d8d6037becbc22/apps/rush-lib/src/api/EnvironmentConfiguration.ts#L10) similar to `RUSH_TEMP_FOLDER` and `RUSH_PREVIEW_VERSION`.
