### ISSUE TITLE
Want a per rush project way to set auth token

### ISSUE THREAD

**Issue by warmsea** [Microsoft/web-build-tools#540]
Is there a way to set auth token (and other npm configurations) per rush project instead of putting it in "~/.npmrc" which will apply to all projects?

I tried to put the auth token in "<project>/common/temp/.npmrc". But it's not working because when I run rush commands, that file will be overwritten.

**Comment by nickpape-msft** [comment]
Yes, you can add it to `common/config/rush/.npmrc` and it will be copied over to `/common/temp/.npmrc` during `rush install` and `rush generate`.

**Comment by warmsea** [comment]
It works! Thank you @nickpape-msft
