### ISSUE TITLE
[api-extractor] impossible to extract both static and instance properties with same name

### ISSUE THREAD

**Issue by giniedp** [Microsoft/web-build-tools#583]
When a static and instance method of a class share the same name like this

```
class MyClass {
  public myMethod() {}
  public static myMethod() {}
}
```

the api extractor will only extract the first method and swallow the other. This is because the `members` property in the api.json is an object.

I propose to separate instance and static members into their own distinct objects. Would that be possible?

**Comment by pgonzal** [comment]
Hey @giniedp thanks for reporting this issue.  We actually encountered it already while implementing the new [\*.d.ts rollup feature](https://github.com/Microsoft/web-build-tools/wiki/API-Extractor-~-Creating-.d.ts-rollups). (Unlike the API review file, the \*.d.ts outputs are compiled code, so they must support every possible construct.)  In the near future I'm going to update the API review file to use this new semantic analyzer.

For the TSDoc standard, we've been discussing the syntax that should be used to reference these types of API items unambiguously.  See [this issue](https://github.com/Microsoft/tsdoc/issues/9).

**Comment by giniedp** [comment]
Great to hear that this is being worked on

**Comment by pgonzal** [comment]
FYI this is now fixed in the my [API Extractor 7 release branch](https://github.com/Microsoft/web-build-tools/tree/pgonzal/ae-overhaul), which is still under development.  I'll update the issue when AE7 is published.

**Comment by giniedp** [comment]
nice

**Comment by octogonz** [comment]
I've confirmed this is working in API Extractor 7.0.17 beta.  If not, please reopen this issue.

To install the beta, you can use this command:

```
npm install -g @microsoft/api-extractor@beta
```

(The "beta" releases have regular ordinary numbers like 7.0.17.  Our [NPM disttag](https://www.npmjs.com/package/@microsoft/api-extractor?activeTab=versions) prevents them from getting installed as the "latest" version if you simply run `npm install -g @microsoft/api-extractor`.  We will update the disttag as soon as version 7 is stable.)
