### ISSUE TITLE
Incorrect parameter at line 240 for @microsoft\gulp-core-build\lib\index.js

### ISSUE THREAD

**Issue by prawnz** [Microsoft/web-build-tools#644]
When trying to load task runner explorer in Visual Studio 2017 the following error is presented

Failed to run "D:\Projects_Nic\Gulpfile.js"...
cmd.exe /c gulp --tasks-simple
D:\Projects_Nic\node_modules\@microsoft\gulp-core-build\lib\index.js:240
function serial(...tasks) {
                ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

Seem like the parameter is incorrect when it is brought down via NPM install. Can you verify?

**Comment by nickpape-msft** [comment]
Does this error occur when you run `cmd.exe /c gulp` ? What version of gulp do you have installed globally? What version of Node.js (`node -v`)?

**Comment by nickpape-msft** [comment]
We are pretty certain the issue is using an outdated version of Node.js that does not support ES6 syntax. Please update Node.js to version 6 LTS (i.e. >6.9.0) or 8 LTS (i.e. >8.9.0).
