### ISSUE TITLE
[rush] "rush publish" should detect if a feed already contains the package at the target version

### ISSUE THREAD

**Issue by lambertwang** [microsoft/web-build-tools#650]
In our automated publishing process, the publish change requests step may fail for whatever reason but it may manage to publish some but not all of the packages. When this happens, future build definitions will attempt to publish the packages that were previously published in the last failed build.
`Forbidden The feed already contains the package 'foo' at version '#.#.#': foo`

It may be nice for rush to detect that a package already exists in the feed at the desired version before attempting to publish the package.

**Comment by pgonzal** [comment]
See PR #654

**Comment by pgonzal** [comment]
@qz2017 are you planning to finish your PR?

**Comment by halfnibble** [comment]
I believe this is fixed in PR #654.
Please reopen if that is not the case.
