### ISSUE TITLE
Problem with "rush version --bump" and peerDependencies

### ISSUE THREAD

**Issue by scsewall** [Microsoft/web-build-tools#668]
"rush version --bump" does not update peerDependencies which then lays a trap for a subsequent "rush check".  The best practice for using peerDependencies is to also set a devDependency for testing purposes.  The package version in the devDependency is updated, but the package version in the peerDependency is not.

**Comment by pgonzal** [comment]
Your PR https://github.com/Microsoft/web-build-tools/pull/699 has been published as `@microsoft/rush/5.0.0-dev.24`.  Please give it a try and close the issue if it works.  Thanks again for fixing this!

**Comment by scsewall** [comment]
After this fix, peerDependencies are properly updated in my scenario.

**Comment by pgonzal** [comment]
Great!
