### ISSUE TITLE
[api-extractor] {@link} AEDoc tag error with api-extractor

### ISSUE THREAD

**Issue by levid-gc** [Microsoft/web-build-tools#676]
When I write comment like this: `@param store - {@link Menu} type instance`, the **api-extractor** will report this error *The @param tag is missing a parameter description*. 

However, when I add something before `{@link}`, like `@param store - xxx {@link Menu} type instance`, and then there be no errors, is it a bug?

**Comment by pgonzal** [comment]
Sounds like a bug. We're doing an API Extractor sprint this month. I'll see if I can fix it. (If the fix is easy, feel free to open a PR.)

**Comment by pgonzal** [comment]
I'm not able to repro this any more.  Seems like it was fixed in API Extractor 6, which introduced the [TSDoc parser](https://github.com/Microsoft/tsdoc).

If not, please reopen this issue.
