### ISSUE TITLE
Subnamespaces only parse when enums are present

### ISSUE THREAD

**Issue by AlexJerabek** [Microsoft/web-build-tools#679]
Given this code...
declare namespace Office {
    namespace Test {
        enum foo {
            x,
            y
        }
        interface TestInterface {
            zz:OtherInterface;
            method(): void;
        }
        interface OtherInterface {
            id: string;
        }
    }

    namespace Test2 {
        interface TestInterface2 {
            zz:OtherInterface2;
            method(): void;
        }
        interface OtherInterface2 {
            id: string;
        }
    }

… only the Test namespace is parsed into the json and yml files. If you add an enum to Test2, then everything works as expected.

**Comment by pgonzal** [comment]
We are doing a sprint this month to improve API Extractor. I'll see if we can address this as part of that work.

**Comment by pgonzal** [comment]
This is fixed by PR #704
