### ISSUE TITLE
typescript 2.9 ready?

### ISSUE THREAD

**Issue by RueDeRennes** [Microsoft/web-build-tools#702]
when i use "api-extractor run", get this error,
Error: Error parsing tsconfig.json content: Unknown compiler option 'declarationMap'.

tsc Version 2.9.2

**Comment by pgonzal** [comment]
Currently API Extractor is using TypeScript 2.4.  We need to upgrade to 2.9.  I'll see if I can get that done sometime in the next week.

**Comment by RueDeRennes** [comment]
i think so too

**Comment by hansl** [comment]
How about using the current directory's TypeScript (if available)?

**Comment by pgonzal** [comment]
FYI this was already fixed in PR https://github.com/Microsoft/web-build-tools/pull/781
