### ISSUE TITLE
[rush] Add a 'variants' feature to support validating multiple dependency sets in the same repo

### ISSUE THREAD

**Issue by ThomasMichon** [Microsoft/web-build-tools#721]
# Summary

Add support for a `--variant` command-line parameter to core Rush commands which can be used to install and link an alternate configuration of `node_modules` based on selected overrides. This option would allow for continuous integration which validates that packages published from a Repo actually support the dependency range declared in their `package.json` file.

```bash
rush install
rush build
rush install --variant old-dependencies
rush build
```

# Concepts

Introduce the concept of a `variant`, which is an override for `common-versions.json` and an associated alternate Shrinkwrap file, which may be checked into the repository alongside the original versions. This variant may be selected and used by adding `--variant <name>` to Rush commands which interact with the Shrinkwrap file, such as `rush install`, `rush update`, `rush link`, and `rush check`.

A variant is created by adding a subfolder under Rush configuration:

```
common/
  config/
    rush/
      variants/
        old-dependencies/ <-- Name of variant
          common-versions.json <-- Overrides for variant
      common-versions.json <-- Original Rush config
```

The expectation is that each `package.json` in the repository may declare support for a range of a dependency, but that `common-versions.json` typically declares a `preferredVersion` for such a dependency, and thus only that version is installed and validated against. The `common-versions.json` under `variants` subfolder may declare a different version of that dependency in `preferredVersions`:

`foo/package.json`:
```json
{
    "dependencies": {
        "dependency-a": "^4.0.0 || ^5.0.0"
    }
}
```

`common/config/rush/common-versions.json`:
```json
{
    "preferredVersions": {
        "dependency-a": "5.0.1"
    }
}
```

`common/config/rush/variants/old-dependencies/common-versions.json`:
```json
{
    "preferredVersions": {
        "dependency-a": "4.13.2"
    }
}
```

Each variant will have its own Shrinkwrap file, which will ensure that it installs deterministically for all consumers.

By default, `rush install` will install the *default* variant. But developers or lab automation may install a different variant by using `rush install --variant old-dependencies`. Developers will also need to create or update the variant's Shrinkwrap file by using `rush update --variant old-dependencies`.

# Modifications

Add `--variant` as a single-argument command line parameter to all Rush commands which depend on or modify the dependency configuration in Rush. These include

- `rush install`
- `rush update`
- `rush check`
- `rush link`

Allow `--variant` to pull automatically from a `RUSH_VARIANT` environment variable, if present, to simplify modification to existing lab automation tasks.

# Benefits

This 'variants' feature will allow repository maintainers to ensure that their published packages truly support the range of dependencies they declare, by providing a way to maintain multiple sets of preferred dependency versions within the repository, and by making it possible to switch to variants at any time before running validation.

Since this feature will add a way to create alternate `common-versions.json` and Shrinkwrap files than the default checked-in versions, it will also provide a clean mechanism to run repo-wide validation against incoming new versions of packages, since a script may easily generate a variant subfolder and configuration, and then install that variant. The given named variant may be added to `.gitignore`, ensuring it does not disturb other local changes.

`.gitignore`:
```
/common/config/rush/variants/dev
```

`common/config/rush/variants/dev/common-versions.json`:
```json
{
    "preferredVersions": {
        "dependency-a": "5.0.1-dev.1"
    }
}
```

```
rush update --variant dev
rush build
```

Such a system could be used to create multi-repo build validation jobs with some additional work.

**Comment by pgonzal** [comment]
We reviewed this design with Thomas today.  We think it’s an insightful idea and useful feature!  The impact on other Rush features seems minimal.  Our main feedback was to declare the variants in rush.json and include descriptions for them.
