### ISSUE TITLE
rush publish --pack --include-all no tarballs created

### ISSUE THREAD

**Issue by firzok** [Microsoft/web-build-tools#735]
I am trying to create tarballs with this command 
`rush publish --pack --include-all`

and it displays the following for two test packages:

`Rush Multi-Project Build Tool 5.0.0 - https://rushjs.io

Starting "rush publish"

Rush publish starts with includeAll and version policy undefined

* DRYRUN: D:\published npm\common\temp\npm-local\node_modules\.bin\npm pack (core\testRush)

* DRYRUN: D:\published npm\common\temp\npm-local\node_modules\.bin\npm pack (core\testRush1)

Rush publish finished successfully.`

I have even tried it with different flags like --release-folder etc but still, I am not able to get the tarballs. Any help is appreciated

**Comment by qz2017** [comment]
Try run with `rush publish --publish --pack  --include-all`.  `rush publish` uses this extra flag `--publish` to tell it is not a dry run.  If you run it without `--publish`, it is a dry-run mode, and the results won't get written to disk.

**Comment by qz2017** [comment]
I think we should replace `--publish` with something more meaningful. Maybe `--not-dry-run`?

**Comment by firzok** [comment]
Thanks qz2017. Yes, you're right, it should be implemented in such a way that when we don't provide a flag it executes and when we want to run as a dry run we can have a flag for that like --dry-run

**Comment by fearthecowboy** [comment]
> I think we should replace `--publish` with something more meaningful. Maybe `--not-dry-run`?

THIS.

**Comment by olivierlacan** [comment]
@qz2017 @octogonz Having a `--publish` flag on a `publish` command indeeds seems misguided and unnecessarily confusing.

**Comment by octogonz** [comment]
We are planning to move most of these CLI parameters into config files and simplify the command line
