### ISSUE TITLE
[rush] Rush does not correctly handle staged file renames.

### ISSUE THREAD

**Issue by iclanton** [Microsoft/web-build-tools#739]
If you rename a file and then stage it in git (i.e. - git sees the file change as a rename instead of as a deletion and creation), the change tracking in Rush fails with an exception.

The issue is that package-deps-hash doesn't parse ([here](https://github.com/Microsoft/web-build-tools/blob/master/libraries/package-deps-hash/src/getPackageDeps.ts#L66-L73)) or handle ([here](https://github.com/Microsoft/web-build-tools/blob/master/libraries/package-deps-hash/src/getPackageDeps.ts#L152-L154)) the `RM` change type.

**Comment by nickpape-msft** [comment]
Looks like a bug we should fix. Should be easy enough.

**Comment by iclanton** [comment]
Yeah the fix should be easy. I'm surprised nobody has hit it until now.

**Comment by iclanton** [comment]
Fixed.
