### ISSUE TITLE
[rush] Is it possible to use Rush version command with an arbitrary version?

### ISSUE THREAD

**Issue by HipsterZipster** [Microsoft/web-build-tools#741]
Hi,
We are currently using rush 4.3.2 with pnpm, but are planning to upgrade to 5 within the next month or so. 

We do not plan on using the changelog management features of Rush, but would like the ability to run "npm version 1.2.3" on all of our packages so that both:
1. The top level `version` property of each `package.json` is updated 
2. The package dependencies that exist within the repo are also updated in each `package.json`

For example:

## BEFORE

Package A:
```json
{
  "name": "package-a",
  "version": "0.0.0",
  "dependencies": [
    "package-b": "0.0.0"
  ]
}
```

Package B:
```json
{
  "name": "package-b",
  "version": "0.0.0"
}
```

`rush version 1.2.3`

## AFTER

Package A:
```json
{
  "name": "package-a",
  "version": "1.2.3",
  "dependencies": [
    "package-b": "1.2.3"
  ]
}
```

Package B:
```json
{
  "name": "package-b",
  "version": "1.2.3"
}
```

**Comment by nickpape-msft** [comment]
Hey there, Rush has a concept called "version policies" that can be configured to work similarly to how you are describing... It is somewhat described by this page, if you scroll to the "What is a version policy?" and "Two types of version policies" sections.

You can create what is known as a "lock-step" policy. This is a policy which enforces a single version number for all the packages in a particular group. You would create a file in `/common/config/rush` called `version-policies.json`, with something like:

```json
[
  {
    "policyName": "rush",
    "definitionName": "lockStepVersion",
    "version": "1.5.0",
    "nextBump": "patch"
  }
]
```

You also have to update `rush.json` and associate the projects with this policy, e.g.:

```
{
  "packageName": "@microsoft/rush",
  "projectFolder": "apps/rush",
  "versionPolicyName": "rush"
},
```

Note, we actually do something like this already for Rush:

https://github.com/Microsoft/web-build-tools/blob/master/rush.json#L44
https://github.com/Microsoft/web-build-tools/blob/master/common/config/rush/version-policies.json

You would then run a command:

`rush version --bump`

This would update the `package.json` and `version-policy.json` files [as well as dependencies].

You can then use:

`rush publish –include-all`

To re-publish everything that has had its version bumped.

**Comment by HipsterZipster** [comment]
Thank you, but am I able to pass in an arbitrary version?

**Comment by nickpape-msft** [comment]
Not currently, no. You would just set the current version in `version` and the type of bump in `nextBump`. Although we can consider that as a feature request.

@qz2017  for awareness.

**Comment by HipsterZipster** [comment]
Hi @nickpape-msft,
Our builds are versioned automatically by our CI server so this would be a really great feature for us and would replace a bunch of our custom scripts. 

If this would be a community contribution, would it make sense to add the ability to accept a version string to the `--override-bump` flag in https://github.com/Microsoft/web-build-tools/blob/master/apps/rush-lib/src/cli/actions/VersionAction.ts#L123 and https://github.com/Microsoft/web-build-tools/blob/master/apps/rush-lib/src/cli/actions/VersionAction.ts#L177 
and then call a new method instead of `bump` https://github.com/Microsoft/web-build-tools/blob/master/apps/rush-lib/src/logic/VersionManager.ts#L63 that doesn't look at version policies and just updates the versions for every package?

**Comment by qz2017** [comment]
You can specify any version you want for lock-step version policy. To do that, use `rush version --ensure-version-policy --override-version x.y.z`.

**Comment by qz2017** [comment]
`rush version --ensure-version-policy --override-version x.y.z --version-policy yourPolicyNam`

**Comment by HipsterZipster** [comment]
Amazing! thank you so much for your help @qz2017 and @nickpape-msft

**Comment by pgonzal** [comment]
Should we close this issue?

**Comment by HipsterZipster** [comment]
This worked great!
