### ISSUE TITLE
"rush purge --help" not working properly

### ISSUE THREAD

**Issue by scsewall** [Microsoft/web-build-tools#751]
It does not display the help message and does the purge anyway...

**Comment by nickpape-msft** [comment]
This didn't repro for me... Which version of Rush are you on?

![image](https://user-images.githubusercontent.com/17131271/43020720-cfbc3ca6-8c15-11e8-9a05-74b58bbcf4a6.png)

**Comment by scsewall** [comment]
My project was configured to use Rush 5.0.0, but I had a global install of Rush 4.3.2.  Once I upgraded my global install to 5.0.0, then this problem went away.  The Rush changelog for 4.3.3 mentions something about removing the undocumented "rush purge" command, so that probably explains it.  The "rush purge" command must have been handled by the global install of 4.3.2 instead of the project-specified 5.0.0 version.  Anyway, I am marking this as closed.
