### ISSUE TITLE
[rush] $schema directive cannot be used with version-policies.schema.json

### ISSUE THREAD

**Issue by enten** [microsoft/web-build-tools#785]
```
issue kind: question
package: @microsoft/rush-lib
```

### Question

_Has version-policies.schema.json deployment failed?_

### Log message which motivates the question

A warning message in vscode when I tried to write a Rush `version-policies.json` config file base on [version-policies.schema.json](https://github.com/Microsoft/web-build-tools/blob/master/apps/rush-lib/src/schemas/version-policies.schema.json):
> Unable to load schema from 'https://developer.microsoft.com/json-schemas/rush/v5/version-policies.schema.json'

### Repro steps

```shell
$ curl -I https://developer.microsoft.com/json-schemas/rush/v5/version-policies.schema.json

HTTP/2 401
cache-control: private
content-length: 2266
content-type: text/html; charset=utf-8
server: Microsoft-IIS/10.0
x-frame-options: SAMEORIGIN
x-aspnet-version: 4.0.30319
ms-correlationid: a04dc500-b90b-45aa-be83-a2663e6e468a
x-powered-by: ASP.NET
x-ua-compatible: IE=edge
date: Sat, 25 Aug 2018 12:39:57 GMT
strict-transport-security: max-age=31536000; includeSubDomains

```

**Comment by pgonzal** [comment]
This file format was unfortunately designed with a JSON array as its root node, instead of a JSON object. As such, it is not possible to use a `$schema` directive in this config file. That is why we didn't publish this particular schema.

We are planning to redesign this config file, but it will be a breaking change, so it's not a quick fix. It will probably be rolled together with some other improvements/simplifications for the publishing feature.

**Comment by pgonzal** [comment]
Retitling issue to track the work that needs to be done here

**Comment by pgonzal** [comment]
Marked as "blocked" because this will be a breaking change for the config file format.  The work is pretty easy, but it needs to be rolled together with the other planned design changes for the publishing/versioning config files.

**Comment by halfnibble** [comment]
Can someone explain this to me? Is this still an issue?

**Comment by octogonz** [comment]
@halfnibble it is still an issue, but @iclanton has plans to revamp the publishing story for Rush (tracked by metaissue https://github.com/microsoft/web-build-tools/issues/904).  That would be the appropriate time to make a breaking change to this file format.

Let's go ahead and close this issue for now.  We have a lot of experience with JSON schemas, so I'm pretty confident we'll remember to fix this issue when we make breaking changes to the schema.
