### ISSUE TITLE
Failure when trying to install latest rush version

### ISSUE THREAD

**Issue by armansabaa** [Microsoft/web-build-tools#819]
Im new to microsoft/rush, trying to install by running 'npm install -g @microsoft/rush' i get:

npm ERR! Unexpected end of JSON input while parsing near '...ypes/mocha":"2.2.38",'

Windows 10
Node version v8.9.4
NPM version v6.4.0

**Comment by armansabaa** [comment]
Didnt work from first time, tried it more than once but worked finally
1) npm clean cache --force
2) npm install -g @microsoft/rush

**Comment by nickpape-msft** [comment]
We don't have a postinstall script or anything crazy, so installing should be straightforward. I would expect this to be an NPM failure (ever version of NPM since 4.6.0 has a host of known bugs).
