### ISSUE TITLE
[rush] Git hooks in Rush

### ISSUE THREAD

**Issue by natalieethell** [Microsoft/web-build-tools#821]
Could Rush support git hooks?

**Comment by pgonzal** [comment]
If we had Rush manage this, I'm thinking it could be extremely simple.  I don't even think we'd need to cook up a fancy config section.  It could just be a folder like **common/config/git-hooks** that gets copied into **.git/hooks**, deleting whatever is already there.  Maybe this happens automatically as part of `rush install`.

When we looked at Husky, it's focused on mapping Git's scripts to NPM lifecycle scripts, which is great for getting people started.  But at the point where you're setting up a serious multi-project monorepo, I don't think that developer's going to be intimidated by the requirement to write a Bash script that invokes their script.
