### ISSUE TITLE
[Gulp-Core-Build-Typescript] wrong package version when overriding with overridePackagePath config

### ISSUE THREAD

**Issue by GolaWaya** [microsoft/web-build-tools#835]
When overridePackagePath is set, gulp still displays the default package version leading to confusion regarding which version of typescript or tslint is doing the work.

**Comment by hohenp** [comment]
Helo GolaWaya
I also had to override typesscript Version using overridePackagePath and yes, it still consoles 
[tsc] typescript version: 2.4.2

Do you have Problems, that tsc is now outputting the files not into the lib Folder as it does without the overridePackagePath? I do now have all compiled files within the src Folder...

**Comment by pgonzal** [comment]
Since the PR was merged, can we close this issue now?  Or is something still unresolved?

**Comment by halfnibble** [comment]
Closing due to merge of related PR. Please reopen if further work is needed.
