### ISSUE TITLE
[rush] Using rush tools without installing globally.

### ISSUE THREAD

**Issue by MartynasZilinskas** [Microsoft/web-build-tools#842]
We use repository [package.json](https://github.com/SimplrJS/react-forms/blob/master/package.json) to install rush and use from local `node_modules/` with `npx`.

```sh
$ npx rush install
```

After running the command I am receiving this warning:
```
Warning: A phantom "node_modules" folder was found. This defeats Rush's protection against NPM phantom dependencies and
may cause confusing build errors. It is recommended to delete this folder:
"D:\Projects\simplrjs\react-forms\node_modules"
```

**Comment by pgonzal** [comment]
This was a new protection introduced in Rush 5.  Please take a look a this doc:

https://rushjs.io/pages/advanced/phantom_deps/

**Comment by pgonzal** [comment]
@MartynasZilinskas can we close this issue?

**Comment by MartynasZilinskas** [comment]
Yeah, I am closing this issue.
