### ISSUE TITLE
[Rush] Postinstall script?

### ISSUE THREAD

**Issue by light24bulbs** [Microsoft/web-build-tools#862]
Is there a way to run a postinstall script for rush?  I need to throw something in the common/temp directory.

PostCSS expects there to be a postcss.config.js config file in the project root, and since it is installed in /temp now, it expects there to be a config file there.

**Comment by pgonzal** [comment]
Take a look at the [postRushInstall](https://github.com/Microsoft/rush-example/blob/59cddfedc0c5cf24146babc0aba7b5865978f828/rush.json#L186) event hook.

**Comment by sveisvei** [comment]
@light24bulbs Hey! How did you solve this?

**Comment by yume-chan** [comment]
I resolve this by adding this to `commands` in command-line.json:

```json
{
    "commandKind": "bulk",
    "name": "postinstall",
    "summary": "Run all postinstall scripts",
    "ignoreMissingScript": true,
    "enableParallelism": true,
    "ignoreDependencyOrder": true,
    "safeForSimultaneousRushProcesses": true
}
```

And this to `eventHooks` in rush.json:

```json
"postRushInstall": [
    "rush postinstall"
],
```
