### ISSUE TITLE
[rush/ts-command-line] Rush doesn't support `--no-color` flag.

### ISSUE THREAD

**Issue by MartynasZilinskas** [Microsoft/web-build-tools#865]
We are using VSTS CI, and it doesn't support colors:
![image](https://user-images.githubusercontent.com/562658/46586952-203f8280-ca8e-11e8-9fc6-5ff38ae98365.png)

[Colors](https://www.npmjs.com/package/colors#disabling-colors) dependency supports `--no-color` flag.  But after running another build I have received an error:
```
2018-10-07T20:54:33.4192780Z rush install: error: Unrecognized arguments: --no-color.
```

**Comment by pgonzal** [comment]
Try setting `FORCE_COLOR=0`.  Rush will pass this environment variable through to your toolchain, and if you use the **colors** library, it honors this environment variable.

Sadly, **colors** considers the environment variable only \*after\* probing for [3 different command-line](https://github.com/Marak/colors.js/blob/1d560880e2341a7a541afa5620adae4809b0571c/lib/system/supports-colors.js#L35) options.   But if I remember correctly, your toolchain can straighten this out using `colors.enable()` or `colors.disable()`.

**Comment by MartynasZilinskas** [comment]
> BTW I believe we considered supporting a command-line option also, but we realized that colors-or-not is an environmental aspect that is inherited by child processes, so shell environment variables seemed like a better design.

I like environment variables more for this thing.

I have tried using `FORCE_COLOR=0` environment variable, and it works. Thank you.

**Comment by pgonzal** [comment]
After thinking about this some more, I think Rush can probably set `FORCE_COLOR` correctly for you in most cases.  See issue https://github.com/Microsoft/web-build-tools/issues/872
