### ISSUE TITLE
Replace deprecated dependency gulp-util

### ISSUE THREAD

**Issue by semenyakNik** [Microsoft/web-build-tools#879]
gulp-util has been deprecated. Continuing to use this dependency may prevent the use of web-build-tools with version 4 of Gulp.

The README.md lists alternatives for all the components so a simple replacement should be enough.

See:
- https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
- gulpjs/gulp-util#143

**Comment by pgonzal** [comment]
Fixed in gulp-core-build 3.8.32

**Comment by pgonzal** [comment]
Thanks again for your PR!
