### ISSUE TITLE
[rush] Allow global custom commands to be marked as safeForSimultaneousRushProcesses

### ISSUE THREAD

**Issue by acoates-ms** [Microsoft/web-build-tools#887]
Our build command has a lot of different parameters that control various slices of the build.  Currently we have a package.json in the root which is basically just used as a collections of scripts.  I want to get rid of this package.json and replace the scripts with global rush commands, which allows better documentation etc.

However, I don’t see an obvious way to get the global commands to do what I want.

We have several PR build definitions that run the rush build command with various different parameters.  We currently have a npm script for each of these, so that we can synchronize parameter changes between the build definition and the code, and to allow developers to easily trigger builds matching the PR builds for local testing:

Current Package.json: 
````
“scripts”: {
                “build-ci-one” “node common/scripts/install-run-rush.js build --param-one --param-one-a …”,
                “build-ci-two” “node common/scripts/install-run-rush.js build --param-two --param-two-b …”
}
````

I’d like to formalize these as global rush commands, but I can’t trigger a rush build command from a rush global command because it says:
Another rush command is already running in this repository.

In command-line.json:
````
“commands”: [
{
                “name”: “buildone”,
                “shellCommand”: “node common/scripts/install-run-rush.js build --param-one --param-one-a …”,
}]
````

To make it work, we could expose safeForSimultaneousRushProcesses as a config option for Rush global commands.  That’s probably not very much work.

**Comment by pgonzal** [comment]
Right, basically [this option](https://github.com/Microsoft/web-build-tools/blob/3e52b2ed4d2a03c19918fba81cd94b6e615eb06f/apps/rush-lib/src/cli/actions/BaseRushAction.ts#L26) should be exposed as part of [this schema](https://github.com/Microsoft/web-build-tools/blob/3e52b2ed4d2a03c19918fba81cd94b6e615eb06f/apps/rush-lib/src/cli/scriptActions/GlobalScriptAction.ts#L14).

This seems like a pretty good feature to me.

**Comment by pgonzal** [comment]
I'll see if we can get some time to implement it. Or if someone else wants to contribute a PR, that would be great too.  :-)
