### ISSUE TITLE
[rush] "publish --pack" fails with yarn because yarn pack names files differently

### ISSUE THREAD

**Issue by light24bulbs** [Microsoft/web-build-tools#897]
`yarn pack` puts a `v` in front of the version name of the file, and rush doesn't handle this properly when copying the packed file to artifacts. 

```
Starting "rush publish"

Rush publish starts with includeAll and version policy undefined

* EXECUTING: common/temp/yarn-local/node_modules/.bin/yarn pack (dev-server)
yarn pack v1.9.4
success Wrote tarball to "dev-server-v0.0.1.tgz".  # NOTICE THE V HERE!!!!!!!!!!!!
✨  Done in 0.11s.

ERROR: ENOENT: no such file or directory, rename
'dev-server/dev-server-0.0.1.tgz' ->
'common/temp/artifacts/packages/dev-server-0.0.1.tgz'
```

Seems like rush `publish --pack` is broken with yarn currently

**Comment by pgonzal** [comment]
This sounds very similar to the other issue we found.  See PR https://github.com/Microsoft/web-build-tools/pull/883

For now we're not attempting to map the package manager command lines to Yarn.  Instead we simply invoke "npm" to perform publishing.

**Comment by pgonzal** [comment]
Oh was this already fixed by 883?
