### ISSUE TITLE
[api-extractor] Ability to name API review files

### ISSUE THREAD

**Issue by aeulitz** [Microsoft/web-build-tools#932]
React/Native library projects are prone to have platform-specific differences in their public API (e.g. to represent platform-specific UI paradigms). It would be great if AE would allow to customize the name of API review files to accommodate platform-specific API differences, e.g. "package.android.api.ts" or "package.ios.api.ts".

Note that today (AE 6.0.2), the effect of the above feature request can be achieved by encoding the platform into the name of the review file folder via the 'apiReviewFile.apiReviewFolder' setting.

**Comment by pgonzal** [comment]
@aeulitz is the workaround that you described satisfactory?  If so, should we close the issue?

Otherwise, if you think it would be useful to have an explicit configuration option for this, could you propose a design?  Should be pretty simple.

**Comment by octogonz** [comment]
Fixed in https://github.com/Microsoft/web-build-tools/pull/1206

**Comment by octogonz** [comment]
@aeulitz  This fix was published.  The current API Extractor 7 release candidate is 7.0.38.
