### ISSUE TITLE
[api-extractor] Forgotten exports are sometimes importable from .d.ts rollups

### ISSUE THREAD

**Issue by pgonzal** [Microsoft/web-build-tools#941]
Suppose a package's **index.d.ts** file looks like this:

**some-library/src/index.d.ts**
```ts
import B from './B'; // forgotten export

export class A extends B {    
  g(): void { }
}
```

Because `B` was not exported from **index.ts**, when API Extractor generates the .d.ts rollup, it includes `B` but omits the `export` keyword, like this:

**some-library/dist/index.d.ts**
```ts
declare class B { 
  f(): void;
}

export declare class A extends B {
  g(): void;
}
```

In other words, we need to describe the interface of B, but people shouldn't be able to import it.

However, the compiler sometimes allows it to be imported anyway:

**consumer/src/example.ts**
```ts
import { B } from 'that-library'; // <-- should be a compile error

let b = new B(); // <-- fails at runtime because "B" is undefined
```

**Comment by pgonzal** [comment]
@DanielRosenwasser pointed out that we can avoid this issue by emitting `export { }` at the bottom of the index.d.ts file.

Not sure why it works, but I confirmed that it does work.

**Comment by nickpape-msft** [comment]
Seems like a compiler bug.
