### ISSUE TITLE
[rush] Two-pass "rush version" and "rush publish" fails to push Git tags

### ISSUE THREAD

**Issue by ThomasMichon** [microsoft/web-build-tools#944]
The vanilla pathway for `rush publish` is susceptible to race conditions if `package.json` files are modified before a continuous integration job can commit the version updates back to the master branch.
To deal with this, a two-pass Publish flow can be created by doing the following:
```
rush version
rush install; rush build
rush publish --include-all
```
The `version` action performs the bump and checks in the changes in a very short time window. The `--include-all` flag to `publish` action then makes Rush re-publish all valid packages, avoiding re-publishing existing versions.

Unfortunately, there is a bug in the second flow, involving writing tags back to the repository. At the end of `rush publish --include-all`, Rush attempts the following:
```
git push origin head:master --follow-tags
```
The tags are pushed, but the attempt to set `origin/master` to `head` can easily fail if anyone has pushed a new change in while the CI build was running.

I believe that the `head:master` is unnecessary in the `rush publish --include-all` flow and that it might be better to do only
```
git push --tags
```

It might be safest to accept a `--no-push-target` (or similar) argument to `rush publish` to make such a change opt-in. Or this change could be made in-place only when using `--include-all`.

**Comment by iclanton** [comment]
We believe this issue is fixed by #1318. If you're still seeing this issue, please reopen this issue or open a new issue.
