### ISSUE TITLE
[rush] `rush install` fails currently, as "flatmap-stream" package is gone.

### ISSUE THREAD

**Issue by adventure-yunfei** [Microsoft/web-build-tools#961]
rush version: 5.5.2.
Error details: `404 Not Found: https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.2.tgz`

Seems npm quickly unpublished this package (the reason should be https://github.com/dominictarr/event-stream/issues/116):

```
$ npm info flatmap-stream
npm ERR! code E404
npm ERR! 404 Unpublished by npm-support on 2018-11-26T17:18:17.658Z
...
```

**Comment by iclanton** [comment]
This PR should fix this issue in WBT: https://github.com/Microsoft/web-build-tools/pull/962

**Comment by iclanton** [comment]
Closing this issue as WBT is now fixed. Please reopen if that wasn't the problem you were having.
