### ISSUE TITLE
@microsoft/load-themed-styles missing AMD version since 1.8.27

### ISSUE THREAD

**Issue by aftab-hassan** [Microsoft/web-build-tools#971]
This issue is moved over from office-ui-fabric-react (original issue [here](https://github.com/OfficeDev/office-ui-fabric-react/issues/7252)).

@microsoft/load-themed-styles is missing AMD version since 1.8.27.

1.8.27
![1 8 27](https://user-images.githubusercontent.com/8922176/49308422-1eda7700-f48d-11e8-94c2-1bca64ce3fef.png)

1.8.26
![1 8 26](https://user-images.githubusercontent.com/8922176/49308438-2c8ffc80-f48d-11e8-98db-602d86fc0b9d.png)

**Comment by iclanton** [comment]
https://github.com/Microsoft/web-build-tools/pull/973

**Comment by iclanton** [comment]
The latest published package has this fixed: https://unpkg.com/@microsoft/load-themed-styles@1.8.44/
![image](https://user-images.githubusercontent.com/5010588/49320356-0763b400-f4b6-11e8-8e6a-f37720bed3b3.png)

**Comment by KevinTCoughlin** [comment]
> 
> 
> The latest published package has this fixed: https://unpkg.com/@microsoft/load-themed-styles@1.8.44/
> ![image](https://user-images.githubusercontent.com/5010588/49320356-0763b400-f4b6-11e8-8e6a-f37720bed3b3.png)

Many thanks @iclanton!
