### ISSUE TITLE
[rush] Git hooks feature causes Rush commands to fail in worktrees

### ISSUE THREAD

**Issue by ecraig12345** [Microsoft/web-build-tools#990]
If the current directory is a [Git worktree](https://git-scm.com/docs/git-worktree) (rather than a full copy of a repo), the new Git hooks feature causes rush commands to fail:
```
Rush Multi-Project Build Tool 5.5.3 - https://rushjs.io

Starting "rush install"

Ignoring Git validation because this is not a Git working folder.

Found files in the "common/git-hooks" folder.

ERROR: EEXIST: file already exists, mkdir 'D:\git\fabric-react2\.git'
```

This is because instead of having a `.git` directory, a worktree has a `.git` *file* containing the path to the real Git metadata directory. For example:
```
gitdir: D:/git/fabric-react/.git/worktrees/fabric-react2
```

I just made a [change](https://github.com/rwjblue/git-repo-info/pull/42) to `git-repo-info` to make it return the directories containing Git metadata for the worktree and for the repo all-up. Once that's published, Rush can be updated to put hooks in the correct directory for the current worktree.

(If anyone is curious, [this blog post](https://spin.atomicobject.com/2016/06/26/parallelize-development-git-worktrees/) has a good explanation of the appeal of worktrees.)

**Comment by ecraig12345** [comment]
@nchlswhttkr @pgonzal @natalieethell FYI -- I plan to fix this myself, but wanted to let you know about the issue since you've done (or reviewed) related work.

**Comment by pgonzal** [comment]
Thanks very much @ecraig12345 !
