### ISSUE TITLE
[load-themed-styles] SSR issues due to document references

### ISSUE THREAD

**Issue by bkniffler** [Microsoft/web-build-tools#992]
While using fabric ui, there is issues with load-themed-styles on nextJS SSR. 

For example `registerStyles` (https://github.com/Microsoft/web-build-tools/blob/master/libraries/load-themed-styles/src/index.ts#L390).

`shouldUseCssText` meanwhile will check for document undefined.

**Comment by bkniffler** [comment]
I think the main cause is the `loadStyles` method which is used pretty often in fabric ui react. This PR fixes this: https://github.com/Microsoft/web-build-tools/pulls

**Comment by pgonzal** [comment]
Fixed by #993 in 1.8.50.  Thanks @bkniffler!
